Repository FEniCS/dolfinx, pull requests merged in 2022-09, with the labels that each got.

#2334 Remove template function `copy_N`
  cpp/dolfinx/common/utils.h
  cpp/dolfinx/fem/Expression.h
  cpp/dolfinx/fem/assemble_matrix_impl.h
  cpp/dolfinx/fem/assemble_scalar_impl.h
  cpp/dolfinx/fem/assemble_vector_impl.h
  cpp/dolfinx/fem/discreteoperators.h
  cpp/dolfinx/fem/dofmapbuilder.cpp
  cpp/dolfinx/geometry/BoundingBoxTree.cpp
  cpp/dolfinx/io/XDMFFile.cpp
  cpp/dolfinx/io/xdmf_utils.h
  cpp/dolfinx/mesh/Mesh.cpp
  cpp/dolfinx/mesh/Topology.cpp
Labels: housekeeping

#2337 Eliminate ghost mode
  .github/workflows/intel.yml
  cpp/demo/hyperelasticity/main.cpp
  cpp/demo/interpolation-io/main.cpp
  cpp/demo/poisson/main.cpp
  cpp/demo/poisson_matrix_free/main.cpp
  cpp/dolfinx/common/MPI.h
  cpp/dolfinx/common/Scatterer.cpp
  cpp/dolfinx/graph/partition.cpp
  cpp/dolfinx/graph/partitioners.cpp
  cpp/dolfinx/mesh/Mesh.cpp
  cpp/dolfinx/mesh/Mesh.h
  cpp/dolfinx/mesh/Topology.cpp
  cpp/dolfinx/mesh/Topology.h
  cpp/dolfinx/mesh/generation.cpp
  cpp/dolfinx/mesh/generation.h
  cpp/dolfinx/mesh/graphbuild.cpp
  cpp/dolfinx/mesh/utils.cpp
  cpp/dolfinx/mesh/utils.h
  cpp/dolfinx/refinement/utils.cpp
  cpp/test/io.cpp
  cpp/test/matrix.cpp
  cpp/test/mesh/distributed_mesh.cpp
  python/doc/source/conf.py
  python/dolfinx/io/gmshio.py
  python/dolfinx/io/utils.py
  python/dolfinx/mesh.py
  python/dolfinx/wrappers/mesh.cpp
  python/test/unit/fem/test_assembler.py
  python/test/unit/io/test_adios2.py
  python/test/unit/mesh/test_mesh.py
  python/test/unit/mesh/test_mesh_partitioners.py
Labels: enhancement

#2347 Fix permuting of Lagrange spaces inside mixed elements
  cpp/dolfinx/fem/FiniteElement.cpp
  python/test/unit/fem/test_interpolation.py
Labels: bug

#2353 Fix bug where not all required vertices are added to submesh vertex map
  cpp/dolfinx/mesh/Mesh.cpp
Labels: bug

#2233 Extend submesh to higher order geometries
  cpp/dolfinx/common/IndexMap.cpp
  cpp/dolfinx/la/petsc.cpp
  cpp/dolfinx/mesh/Mesh.cpp
  cpp/dolfinx/mesh/topologycomputation.cpp
  cpp/dolfinx/mesh/utils.cpp
  python/dolfinx/mesh.py
  python/test/unit/mesh/test_higher_order_mesh.py
  python/test/unit/mesh/test_mesh.py
Labels: bug, enhancement

#2356 Remove xtensor
  .github/workflows/macos.yml
  cpp/CMakeLists.txt
  cpp/cmake/templates/DOLFINXConfig.cmake.in
  cpp/demo/hyperelasticity/main.cpp
  cpp/demo/interpolation-io/main.cpp
  cpp/demo/poisson/main.cpp
  cpp/demo/poisson_matrix_free/main.cpp
  cpp/dolfinx/CMakeLists.txt
  cpp/dolfinx/fem/DirichletBC.cpp
  cpp/dolfinx/fem/DirichletBC.h
  cpp/dolfinx/fem/Expression.h
  cpp/dolfinx/fem/Function.h
  cpp/dolfinx/mesh/utils.cpp
  cpp/dolfinx/mesh/utils.h
  cpp/test/matrix.cpp
  docker/Dockerfile
  docker/Dockerfile.redhat
  python/CMakeLists.txt
  python/doc/source/installation.rst
  python/dolfinx/wrappers/fem.cpp
  python/dolfinx/wrappers/mesh.cpp
Labels: task

#2360 Run Spack CI in a bare container
  .github/workflows/spack.yml
Labels: testing

#2368 Update readme - Add blank lines before fenced code blocks
  README.md
Labels: housekeeping

#2336 Add Sobolev spaces to custom element
  .github/workflows/intel.yml
  cpp/dolfinx/fem/FiniteElement.cpp
  python/demo/demo_tnt-elements.py
  python/test/unit/fem/test_custom_basix_element.py
  python/test/unit/fem/test_interpolation.py
Labels: enhancement

#2301 Create Basix elements directly, rather than going via UFL
  python/dolfinx/fem/function.py
  python/dolfinx/io/gmshio.py
  python/dolfinx/io/utils.py
  python/dolfinx/mesh.py
Labels: enhancement

#2384 Fix pyvista data interface
  python/dolfinx/plot.py
  python/test/unit/io/test_vtk.py
Labels: bug
