Repository FEniCS/dolfinx, pull requests merged in 2022-11, with the labels that each got.

#2435 Fix incorrect use of std::span
  cpp/dolfinx/fem/Form.h
  cpp/dolfinx/graph/partition.h
  cpp/dolfinx/la/MatrixCSR.h
  cpp/dolfinx/mesh/MeshTags.h
  cpp/dolfinx/refinement/utils.cpp
  python/dolfinx/mesh.py
  python/dolfinx/wrappers/la.cpp
Labels: bug

#2432 Fix unused ElementType
  python/test/unit/fem/test_mixed_element.py
Labels: testing, housekeeping

#2438 Template over assembler kernel and use C++20 concepts
  .github/workflows/build-wheels.yml
  .github/workflows/ccpp.yml
  cpp/dolfinx/common/utils.h
  cpp/dolfinx/fem/DirichletBC.h
  cpp/dolfinx/fem/DofMap.h
  cpp/dolfinx/fem/Form.h
  cpp/dolfinx/fem/assemble_matrix_impl.h
  cpp/dolfinx/fem/assemble_scalar_impl.h
  cpp/dolfinx/fem/assemble_vector_impl.h
  cpp/dolfinx/fem/assembler.h
  cpp/dolfinx/fem/discreteoperators.h
  cpp/dolfinx/fem/utils.h
  cpp/dolfinx/graph/AdjacencyList.h
  cpp/dolfinx/la/utils.h
  cpp/dolfinx/mesh/Geometry.h
  cpp/dolfinx/mesh/Mesh.h
Labels: enhancement, housekeeping

#2441 Install latest doxygen in CI
  docker/Dockerfile
Labels: documentation, docker, ci

#2443 Work-arounds for latest doxygen
  cpp/demo/hyperelasticity/main.cpp
  cpp/demo/interpolation_different_meshes/main.cpp
  cpp/demo/poisson_matrix_free/main.cpp
  cpp/dolfinx/common/TimeLogManager.cpp
  cpp/dolfinx/common/math.h
  cpp/dolfinx/fem/Form.h
  cpp/dolfinx/fem/assembler.h
  cpp/dolfinx/fem/interpolate.h
  cpp/dolfinx/fem/utils.h
  cpp/dolfinx/geometry/utils.cpp
  cpp/dolfinx/graph/AdjacencyList.h
  cpp/dolfinx/graph/ordering.h
  cpp/dolfinx/graph/partition.h
  cpp/dolfinx/la/petsc.cpp
  cpp/dolfinx/la/utils.h
  cpp/dolfinx/mesh/utils.cpp
  cpp/dolfinx/mesh/utils.h
Labels: documentation

#2446 CI updates for new Spack concretiation
  .github/workflows/spack.yml
Labels: ci

#2448 Remove macos-11 from CI
  .github/workflows/macos.yml
Labels: ci

#2447 Support output of floats (real and complex) via ADIOS-2 backends.
  cpp/dolfinx/io/ADIOS2Writers.cpp
  cpp/dolfinx/io/ADIOS2Writers.h
  python/dolfinx/fem/function.py
  python/dolfinx/io/gmshio.py
  python/dolfinx/mesh.py
  python/dolfinx/wrappers/fem.cpp
  python/dolfinx/wrappers/io.cpp
  python/test/unit/io/test_adios2.py
Labels: enhancement, io

#2449 Bump some package versions in Dockerfile
  docker/Dockerfile
Labels: docker, ci

#2452 Remove unused and sort imports in cpp demos
  cpp/demo/poisson/poisson.py
  cpp/demo/poisson_matrix_free/poisson.py
Labels: demo, housekeeping

#2451 Remove deprecated ufl function
  python/dolfinx/fem/function.py
Labels: task, housekeeping

#2450 Pass only required mesh data into assemblers
  cpp/dolfinx/fem/assemble_matrix_impl.h
  cpp/dolfinx/fem/assemble_scalar_impl.h
  cpp/dolfinx/fem/assemble_vector_impl.h
Labels: housekeeping

#2453 Rename public API test to be more meaningful
  python/test/unit/common/test_public_api.py
Labels: housekeeping

#2314 Reusing mesh when saving to Fides
  cpp/dolfinx/io/ADIOS2Writers.cpp
  cpp/dolfinx/io/ADIOS2Writers.h
  python/dolfinx/wrappers/io.cpp
Labels: enhancement

#2459 Pin ipywidgets
  .github/workflows/pyvista.yml
  docker/Dockerfile
Labels: docker

#2465 Avoid petsc gc errors in the tests
  python/test/unit/fem/test_expression.py
  python/test/unit/fem/test_nonlinear_assembler.py
Labels: ci

#2466 Bump to PETSc 3.18
  docker/Dockerfile
Labels: docker, ci

#2468 Add extra MatrixCSR test, and disable
  cpp/test/matrix.cpp
Labels: bug

#2467 Print PETSc version during CMake config
  .circleci/config.yml
  .github/workflows/ccpp.yml
  cpp/CMakeLists.txt
  cpp/dolfinx/common/IndexMap.cpp
  cpp/dolfinx/fem/ElementDofLayout.h
  cpp/dolfinx/fem/FiniteElement.cpp
  python/dolfinx/fem/petsc.py
  python/test/unit/fem/test_expression.py
  python/test/unit/fem/test_fem_pipeline.py
  python/test/unit/fem/test_function.py
  python/test/unit/fem/test_function_space.py
  python/test/unit/io/test_vtk.py
  python/test/unit/mesh/test_higher_order_mesh.py
Labels: bug, build

#2469 Simplify PETSc complex scalar detection
  cpp/CMakeLists.txt
  cpp/cmake/scripts/generate-cmakefiles.py
  cpp/cmake/templates/DOLFINXConfig.cmake.in
  cpp/demo/hyperelasticity/CMakeLists.txt
  cpp/demo/poisson/CMakeLists.txt
  cpp/demo/poisson_matrix_free/CMakeLists.txt
Labels: build, housekeeping

#2470 Small update for Rocky Linux (RedHat) Dockerfile
  docker/Dockerfile.redhat
Labels: ci
