Repository FEniCS/dolfinx, pull requests merged in 2022-03, with the labels that each got.

#2062 Some fixes for dofmap creation on a submesh
  cpp/dolfinx/fem/dofmapbuilder.cpp
  python/test/unit/fem/test_assemble_submesh.py
Labels: bug

#2080 Make mesh construction scalable (and remove MPI all-to-all calls)
  cpp/dolfinx/common/IndexMap.cpp
  cpp/dolfinx/common/MPI.cpp
  cpp/dolfinx/common/MPI.h
  cpp/dolfinx/common/subsystem.cpp
  cpp/dolfinx/graph/ordering.cpp
  cpp/dolfinx/graph/partition.cpp
  cpp/dolfinx/graph/partition.h
  cpp/dolfinx/graph/partitioners.cpp
  cpp/dolfinx/io/xdmf_utils.cpp
  cpp/dolfinx/mesh/Geometry.cpp
  cpp/dolfinx/mesh/Geometry.h
  cpp/dolfinx/mesh/Mesh.cpp
  cpp/dolfinx/mesh/Topology.cpp
  cpp/dolfinx/mesh/graphbuild.cpp
  cpp/dolfinx/mesh/graphbuild.h
  cpp/dolfinx/mesh/utils.cpp
  cpp/dolfinx/refinement/utils.cpp
  cpp/test/unit/mesh/distributed_mesh.cpp
  python/dolfinx/wrappers/graph.cpp
  python/dolfinx/wrappers/mesh.cpp
  python/test/unit/io/test_xdmf_mesh.py
  python/test/unit/mesh/test_dual_graph.py
Labels: enhancement, performance, high-priority

#2056 Add Python interface for ADIOS2-based output formats
  cpp/dolfinx/fem/CoordinateElement.h
  cpp/dolfinx/io/ADIOS2Writers.cpp
  python/dolfinx/io.py
  python/test/unit/io/test_adios2.py
Labels: enhancement

#2086 Fix for exterior facet integrals on a submesh
  cpp/dolfinx/fem/Form.h
  python/test/unit/fem/test_assemble_submesh.py
Labels: bug

#2078 Fix interpolation into serendipity
  cpp/dolfinx/fem/FiniteElement.cpp
  cpp/dolfinx/fem/FiniteElement.h
  cpp/dolfinx/fem/interpolate.h
  python/test/unit/fem/test_interpolation.py
Labels: bug, high-priority

#2094 Remove `common::subsystem`
  cpp/demo/hyperelasticity/main.cpp
  cpp/demo/interpolation-io/main.cpp
  cpp/demo/poisson/main.cpp
  cpp/demo/poisson_matrix_free/main.cpp
  cpp/dolfinx/common/CMakeLists.txt
  cpp/dolfinx/common/dolfin_common.h
  cpp/dolfinx/common/init.cpp
  cpp/dolfinx/common/init.h
  cpp/dolfinx/common/log.cpp
  cpp/dolfinx/common/log.h
  cpp/dolfinx/common/subsystem.cpp
  cpp/dolfinx/common/subsystem.h
  cpp/test/unit/main.cpp
  python/dolfinx/wrappers/caster_mpi.h
  python/dolfinx/wrappers/common.cpp
Labels: proposal

#2095 Skip gemv for identity operators in `interpolation_matrix`
  cpp/dolfinx/fem/discreteoperators.h
Labels: performance
