Repository FEniCS/dolfinx, pull requests merged in 2022-07, with the labels that each got.

#2131 Create submodule for gmsh tools
  python/demo/demo_gmsh.py
  python/dolfinx/io/__init__.py
  python/dolfinx/io/gmshio.py
  python/dolfinx/io/utils.py
  python/setup.py
  python/test/unit/io/test_xdmf_mesh.py
  python/test/unit/mesh/test_higher_order_mesh.py
Labels: proposal

#2278 Remove xtensor code from element code
  cpp/demo/interpolation-io/main.cpp
  cpp/demo/poisson_matrix_free/main.cpp
  cpp/dolfinx/common/math.h
  cpp/dolfinx/fem/CoordinateElement.cpp
  cpp/dolfinx/fem/CoordinateElement.h
  cpp/dolfinx/fem/Expression.h
  cpp/dolfinx/fem/FiniteElement.cpp
  cpp/dolfinx/fem/FiniteElement.h
  cpp/dolfinx/fem/Function.h
  cpp/dolfinx/fem/FunctionSpace.cpp
  cpp/dolfinx/fem/discreteoperators.h
  cpp/dolfinx/fem/interpolate.cpp
  cpp/dolfinx/fem/interpolate.h
  cpp/dolfinx/fem/utils.h
  cpp/dolfinx/graph/partition.h
  cpp/dolfinx/io/ADIOS2Writers.cpp
  cpp/dolfinx/io/vtk_utils.cpp
  cpp/dolfinx/io/xdmf_utils.cpp
  cpp/dolfinx/refinement/plaza.h
  python/demo/demo_elasticity.py
  python/dolfinx/fem/function.py
  python/dolfinx/wrappers/fem.cpp
  python/test/unit/fem/test_discrete_operators.py
  python/test/unit/fem/test_dof_permuting.py
  python/test/unit/fem/test_dofmap.py
  python/test/unit/fem/test_expression.py
  python/test/unit/fem/test_function_space.py
  python/test/unit/fem/test_interpolation.py
Labels: performance

#2283 X is not a property
  python/dolfinx/fem/function.py
Labels: bug

#2285 Bump dependency versions in Dockerfile
  docker/Dockerfile
Labels: docker

#2286 Add basic conda testing to CI
  .github/workflows/conda.yml
Labels: testing, packaging

#2290 Remove non-existent function from C++ docs
  .github/workflows/ccpp.yml
  cpp/doc/source/graph.rst
Labels: documentation

#2291 Zero work array in `fem::CoordinateElement::compute_jacobian_determinant`
  cpp/dolfinx/fem/CoordinateElement.h
Labels: bug

#2293 Remove some function callback from C++ to Python
  cpp/dolfinx/mesh/utils.cpp
  python/dolfinx/fem/forms.py
  python/dolfinx/fem/function.py
  python/dolfinx/wrappers/array.h
  python/dolfinx/wrappers/fem.cpp
  python/dolfinx/wrappers/mesh.cpp
  python/test/unit/fem/test_function.py
  python/test/unit/fem/test_interpolation.py
Labels: enhancement

#2296 Make mypy blocking and fix error
  .github/workflows/ccpp.yml
  python/dolfinx/fem/function.py
Labels: testing, housekeeping

#2295 Simplify Constant construction
  cpp/demo/hyperelasticity/main.cpp
  cpp/dolfinx/fem/Constant.h
  cpp/dolfinx/fem/DirichletBC.h
  cpp/dolfinx/mesh/utils.cpp
  python/dolfinx/fem/bcs.py
  python/dolfinx/fem/function.py
  python/dolfinx/wrappers/fem.cpp
  python/test/unit/fem/test_assembler.py
  python/test/unit/fem/test_bcs.py
  python/test/unit/fem/test_nonlinear_assembler.py
  python/test/unit/mesh/test_cell.py
Labels: enhancement

#2300 Try a MacOS build
  .github/workflows/macos.yml
  README.md
Labels: testing
