Repository FEniCS/dolfinx, pull requests merged in 2022-12, with the labels that each got.

#2479 Add complete oneAPI CI testing
  .github/workflows/docker.yml
  .github/workflows/oneapi.yml
  .github/workflows/sonarcloud.yml
  cpp/demo/hyperelasticity/main.cpp
  cpp/dolfinx/graph/partition.h
  cpp/test/mesh/distributed_mesh.cpp
  docker/Dockerfile.oneapi
  docker/Dockerfile.redhat
  python/demo/demo_cahn-hilliard.py
  python/demo/demo_tnt-elements.py
  python/test/unit/fem/test_bcs.py
  python/test/unit/fem/test_custom_assembler.py
  python/test/unit/fem/test_custom_jit_kernels.py
  python/test/unit/fem/test_fem_pipeline.py
  python/test/unit/io/test_adios2.py
  python/test/unit/log/test_log.py
  python/test/unit/ufl-jit-assemble-chain/test_assembly_derivatives.py
Labels: testing, ci

#2474 Remove use of latest
  .circleci/config.yml
  .github/workflows/ccpp.yml
Labels: ci

#2303 Add release instructions
  ChangeLog.rst
  RELEASE.md
Labels: packaging

#2431 Cmake-format support
  .cmake-format
  .github/workflows/ccpp.yml
  cpp/CMakeLists.txt
  cpp/cmake/modules/FindKaHIP.cmake
  cpp/cmake/modules/FindParMETIS.cmake
  cpp/cmake/modules/FindSCOTCH.cmake
  cpp/cmake/modules/FindUFCx.cmake
  cpp/cmake/post-install/CMakeLists.txt
  cpp/cmake/scripts/generate-cmakefiles.py
  cpp/cmake/templates/DOLFINXConfig.cmake.in
  cpp/cmake/templates/cmake_uninstall.cmake.in
  cpp/demo/CMakeLists.txt
  cpp/demo/hyperelasticity/CMakeLists.txt
  cpp/demo/interpolation-io/CMakeLists.txt
  cpp/demo/interpolation_different_meshes/CMakeLists.txt
  cpp/demo/poisson/CMakeLists.txt
  cpp/demo/poisson_matrix_free/CMakeLists.txt
  cpp/dolfinx/CMakeLists.txt
  cpp/dolfinx/common/CMakeLists.txt
  cpp/dolfinx/fem/CMakeLists.txt
  cpp/dolfinx/geometry/CMakeLists.txt
  cpp/dolfinx/graph/CMakeLists.txt
  cpp/dolfinx/io/CMakeLists.txt
  cpp/dolfinx/la/CMakeLists.txt
  cpp/dolfinx/mesh/CMakeLists.txt
  cpp/dolfinx/nls/CMakeLists.txt
  cpp/dolfinx/refinement/CMakeLists.txt
  cpp/test/CMakeLists.txt
  docker/Dockerfile
  python/CMakeLists.txt
Labels: housekeeping

#2482 Fix infinite recursion for `dolfinx.fem.Constant.__float__()` calls
  python/dolfinx/fem/function.py
  python/test/unit/fem/test_constant.py
Labels: bug

#2433 Add demo on scattering boundary conditions (time-harmonic Maxwell's equations)
  python/demo/demo_scattering_boundary_conditions/analytical_efficiencies_wire.py
  python/demo/demo_scattering_boundary_conditions/demo_scattering_boundary_conditions.py
  python/demo/demo_scattering_boundary_conditions/mesh_wire.py
Labels: demo

#2358 Bump minimum CMake to 3.19 and introduce version ranges
  cpp/CMakeLists.txt
  cpp/cmake/modules/FindParMETIS.cmake
  cpp/cmake/modules/FindUFCx.cmake
  cpp/cmake/scripts/generate-cmakefiles.py
  cpp/dolfinx/CMakeLists.txt
Labels: enhancement, build

#2493 Revert CMake ranges requirement for ParMETIS
  cpp/CMakeLists.txt
  cpp/cmake/modules/FindParMETIS.cmake
Labels: build

#2495 Update oneAPI dockerfile
  docker/Dockerfile.oneapi
Labels: ci

#2496 Fix docker tag for CircleCI
  .circleci/config.yml
Labels: ci
