Repository FEniCS/dolfinx, pull requests merged in 2022-10, with the labels that each got.

#2391 Const consistency improvements
  cpp/demo/interpolation-io/main.cpp
  cpp/dolfinx/fem/DirichletBC.h
  cpp/dolfinx/fem/Expression.h
  cpp/dolfinx/fem/Form.h
  cpp/dolfinx/fem/interpolate.h
  cpp/dolfinx/fem/utils.cpp
  cpp/dolfinx/fem/utils.h
  cpp/dolfinx/io/ADIOS2Writers.cpp
  cpp/dolfinx/io/ADIOS2Writers.h
  cpp/dolfinx/io/XDMFFile.cpp
  cpp/dolfinx/io/XDMFFile.h
  cpp/dolfinx/la/Vector.h
  cpp/dolfinx/mesh/Geometry.h
  cpp/dolfinx/mesh/Mesh.cpp
  cpp/dolfinx/mesh/MeshTags.h
  cpp/dolfinx/mesh/Topology.cpp
  cpp/dolfinx/mesh/Topology.h
  cpp/dolfinx/refinement/plaza.cpp
  python/dolfinx/wrappers/fem.cpp
  python/dolfinx/wrappers/io.cpp
  python/dolfinx/wrappers/la.cpp
  python/dolfinx/wrappers/mesh.cpp
Labels: housekeeping

#2385 Check MPI error codes
  README.md
  cpp/dolfinx/common/IndexMap.cpp
  cpp/dolfinx/common/MPI.cpp
  cpp/dolfinx/common/MPI.h
  cpp/dolfinx/common/Scatterer.cpp
  cpp/dolfinx/common/Scatterer.h
  cpp/dolfinx/common/Table.cpp
  cpp/dolfinx/common/utils.h
  cpp/dolfinx/mesh/graphbuild.cpp
Labels: proposal

#2406 Remove unused include header
  cpp/dolfinx/common/defines.cpp
Labels: housekeeping

#2407 Refactor log
  cpp/dolfinx/common/log.cpp
Labels: housekeeping

#2411 Improve `create_submesh` performance
  cpp/dolfinx/mesh/Mesh.cpp
Labels: performance
