Repository FEniCS/dolfinx, pull requests merged in 2022-08, with the labels that each got.

#2311 Enable zlib for hdf5 in docker images
  docker/Dockerfile
Labels: build, docker

#2318 init cmake_args with $CMAKE_ARGS in Python build
  python/setup.py
Labels: build

#2320 Bump versions of various dependencies in Dockerfile
  .github/workflows/pyvista.yml
  docker/Dockerfile
Labels: housekeeping

#2316 Fix interpolation into vector serendipity
  cpp/dolfinx/fem/interpolate.h
  python/test/unit/fem/test_interpolation.py
Labels: bug

#2309 Add the case of a pair (str, int) to dolfinx.fem.TensorFunctionSpace type hints, second argument
  python/dolfinx/fem/function.py
Labels: enhancement, documentation

#2307 Fix minor inconsistency in `compute_jacobian_inverse`
  cpp/dolfinx/fem/CoordinateElement.h
Labels: housekeeping

#2333 Fix various typos
  cpp/CMakeLists.txt
  cpp/dolfinx/CMakeLists.txt
  cpp/dolfinx/common/IndexMap.h
  cpp/dolfinx/common/MPI.cpp
  cpp/dolfinx/common/MPI.h
  cpp/dolfinx/common/Scatterer.h
  cpp/dolfinx/common/loguru.cpp
  cpp/dolfinx/common/loguru.hpp
  cpp/dolfinx/common/sort.h
  cpp/dolfinx/common/utils.h
  cpp/dolfinx/fem/DirichletBC.cpp
  cpp/dolfinx/fem/DirichletBC.h
  cpp/dolfinx/fem/DofMap.h
  cpp/dolfinx/fem/Form.h
  cpp/dolfinx/fem/Function.h
  cpp/dolfinx/fem/assembler.h
  cpp/dolfinx/fem/discreteoperators.h
  cpp/dolfinx/fem/interpolate.h
  cpp/dolfinx/fem/sparsitybuild.cpp
  cpp/dolfinx/graph/partition.cpp
  cpp/dolfinx/graph/partitioners.cpp
  cpp/dolfinx/io/ADIOS2Writers.cpp
  cpp/dolfinx/la/MatrixCSR.h
  cpp/dolfinx/la/SparsityPattern.h
  cpp/dolfinx/la/slepc.h
  cpp/dolfinx/mesh/Mesh.cpp
  cpp/dolfinx/mesh/Mesh.h
  cpp/dolfinx/mesh/MeshTags.h
  cpp/dolfinx/mesh/topologycomputation.cpp
  cpp/dolfinx/nls/NewtonSolver.h
  cpp/test/common/sort.cpp
  cpp/test/matrix.cpp
  docker/Dockerfile
  python/demo/demo_pyvista.py
  python/dolfinx/common.py
  python/dolfinx/fem/forms.py
  python/dolfinx/io/utils.py
  python/test/unit/fem/test_assembler.py
  python/test/unit/geometry/test_bounding_box_tree.py
  python/test/unit/geometry/test_gjk.py
  python/test/unit/la/test_krylov_solver.py
  python/test/unit/mesh/test_mesh.py
Labels: housekeeping
