Repository FEniCS/dolfinx, pull requests merged in 2022-06, with the labels that each got.

#2230 Update `README.md` with conda instructions
  README.md
Labels: documentation

#2224 Fix incorrect `assert` in `Scatterer`
  cpp/dolfinx/common/Scatterer.h
Labels: bug

#2234 Add CFFI to setup.py
  python/setup.py
Labels: build

#2226 Minor improvements to `transfer_cell/facet_meshtags`
  cpp/dolfinx/refinement/utils.cpp
  cpp/dolfinx/refinement/utils.h
Labels: bug

#2225 Flatten integral domains in C++
  cpp/dolfinx/fem/Form.h
  cpp/dolfinx/fem/assemble_matrix_impl.h
  cpp/dolfinx/fem/assemble_scalar_impl.h
  cpp/dolfinx/fem/assemble_vector_impl.h
  cpp/dolfinx/fem/utils.h
  python/dolfinx/wrappers/fem.cpp
Labels: enhancement

#2246 Minor Sphinx config fix
  python/doc/source/conf.py
Labels: bug, documentation

#2244 Allow sparsity pattern to be built from integration entities
  cpp/dolfinx/fem/sparsitybuild.cpp
  cpp/dolfinx/fem/sparsitybuild.h
  cpp/dolfinx/fem/utils.cpp
  cpp/dolfinx/fem/utils.h
Labels: enhancement

#2222 Add missing function parameter names of pybind11 generated functions
  python/dolfinx/wrappers/common.cpp
  python/dolfinx/wrappers/fem.cpp
  python/dolfinx/wrappers/geometry.cpp
  python/dolfinx/wrappers/graph.cpp
  python/dolfinx/wrappers/io.cpp
  python/dolfinx/wrappers/la.cpp
  python/dolfinx/wrappers/log.cpp
  python/dolfinx/wrappers/mesh.cpp
  python/dolfinx/wrappers/nls.cpp
  python/dolfinx/wrappers/refinement.cpp
Labels: enhancement
