Repository FEniCS/dolfinx, pull requests merged in 2023-12, with the labels that each got.

#2917 Set min version for `scikit-build-core`
  python/pyproject.toml
Labels: install

#2921 Bump versions in oneAPI Dockerfile
  docker/Dockerfile.oneapi
Labels: ci

#2924 Add Basix dependency to `pyproject.toml`
  python/pyproject.toml
Labels: install

#2928 Install ptscotch in oneAPI image
  docker/Dockerfile.oneapi
Labels: docker, ci

#2932 Expose `transpose_dofmap` in `dolfinx.fem`
  python/dolfinx/fem/__init__.py
Labels: documentation, backport?

#2933 Remove `dolfinx.nls` from Python documentation
  python/doc/source/api.rst
Labels: documentation, backport?

#2931 Improve overview of online documentation with autosummary
  python/doc/source/conf.py
Labels: documentation, backport?

#2939 Disable Spack CI 0.7.2 Python build
  .github/workflows/spack.yml
Labels: ci

#2940 Update GMSH quadrilateral recombination options to force pure quadrilateral meshes
  python/test/unit/mesh/test_higher_order_mesh.py
Labels: bug, demo, backport?

#2945 Implementation performance improvements when concatenating function spaces for PETSc
  cpp/dolfinx/fem/interpolate.h
  cpp/dolfinx/fem/petsc.h
  cpp/dolfinx/la/petsc.cpp
  cpp/dolfinx/la/petsc.h
  python/demo/demo_mixed-poisson.py
Labels: performance
