Repository FEniCS/dolfinx, pull requests merged in 2023-03, with the labels that each got.

#2562 Fix extraction of mesh from array of forms in lifting
  cpp/dolfinx/fem/assembler.h
  python/test/unit/fem/test_assembler.py
  python/test/unit/fem/test_nonlinear_assembler.py
Labels: bug

#2564 Move location of pybind11 import in `setup.py`
  .github/workflows/macos.yml
  python/setup.py
Labels: build

#2567 Fix in setup.py for Spack builds
  python/setup.py
Labels: build

#2568 Revert setup.py changes
  python/setup.py
Labels: build

#2572 Bump PETSc version in Dockerfile
  .github/workflows/oneapi.yml
  docker/Dockerfile
  docker/Dockerfile.oneapi
  docker/Dockerfile.redhat
Labels: docker

#2582 Add missing include to demo for (`std::numbers`)
  cpp/demo/biharmonic/main.cpp
Labels: bug

#2269 Let integration entities be specified manually
  cpp/dolfinx/fem/Form.h
  cpp/dolfinx/fem/Function.h
  cpp/dolfinx/fem/assembler.h
  cpp/dolfinx/fem/interpolate.cpp
  cpp/dolfinx/fem/interpolate.h
  cpp/dolfinx/fem/utils.cpp
  cpp/dolfinx/fem/utils.h
  python/dolfinx/fem/forms.py
  python/dolfinx/wrappers/fem.cpp
  python/test/unit/fem/test_assemble_domains.py
Labels: enhancement

#2581 Add more versions of DOLFINx to dropdown
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: housekeeping

#2587 Remove some `isinstance`
  python/dolfinx/fem/bcs.py
  python/dolfinx/fem/function.py
Labels: housekeeping

#2588 Fix DOF transformations for custom elements
  cpp/dolfinx/fem/FiniteElement.cpp
  python/test/unit/fem/test_custom_basix_element.py
Labels: bug

#2576 Extend VectorFunctionSpace to custom elements
  python/dolfinx/fem/function.py
Labels: enhancement

#2607 Associate `MeshTags` with `Topology` (and not `Mesh`)
  cpp/demo/biharmonic/main.cpp
  cpp/demo/hyperelasticity/main.cpp
  cpp/demo/interpolation-io/main.cpp
  cpp/demo/interpolation_different_meshes/main.cpp
  cpp/demo/poisson/main.cpp
  cpp/demo/poisson_matrix_free/main.cpp
  cpp/dolfinx/fem/DirichletBC.h
  cpp/dolfinx/fem/Expression.h
  cpp/dolfinx/fem/Function.h
  cpp/dolfinx/fem/FunctionSpace.h
  cpp/dolfinx/fem/assemble_matrix_impl.h
  cpp/dolfinx/fem/assemble_scalar_impl.h
  cpp/dolfinx/fem/assemble_vector_impl.h
  cpp/dolfinx/fem/discreteoperators.h
  cpp/dolfinx/fem/interpolate.h
  cpp/dolfinx/fem/petsc.h
  cpp/dolfinx/fem/utils.cpp
  cpp/dolfinx/fem/utils.h
  cpp/dolfinx/geometry/BoundingBoxTree.h
  cpp/dolfinx/geometry/utils.h
  cpp/dolfinx/io/ADIOS2Writers.cpp
  cpp/dolfinx/io/ADIOS2Writers.h
  cpp/dolfinx/io/VTKFile.cpp
  cpp/dolfinx/io/XDMFFile.cpp
  cpp/dolfinx/io/XDMFFile.h
  cpp/dolfinx/io/vtk_utils.h
  cpp/dolfinx/io/xdmf_function.cpp
  cpp/dolfinx/io/xdmf_mesh.cpp
  cpp/dolfinx/io/xdmf_meshtags.h
  cpp/dolfinx/io/xdmf_utils.cpp
  cpp/dolfinx/mesh/Mesh.h
  cpp/dolfinx/mesh/MeshTags.h
  cpp/dolfinx/mesh/utils.h
  cpp/dolfinx/refinement/plaza.h
  cpp/dolfinx/refinement/refine.h
  cpp/dolfinx/refinement/utils.cpp
  cpp/dolfinx/refinement/utils.h
  cpp/test/mesh/distributed_mesh.cpp
  python/demo/demo_gmsh.py
  python/dolfinx/fem/forms.py
  python/dolfinx/io/utils.py
  python/dolfinx/mesh.py
  python/dolfinx/wrappers/assemble.cpp
  python/dolfinx/wrappers/fem.cpp
  python/dolfinx/wrappers/io.cpp
  python/dolfinx/wrappers/mesh.cpp
  python/dolfinx/wrappers/refinement.cpp
  python/test/unit/fem/test_element_integrals.py
  python/test/unit/io/test_xdmf_meshtags.py
Labels: enhancement, housekeeping
