Repository FEniCS/dolfinx, pull requests merged in 2023-06, with the labels that each got.

#2662 Version updates in docker files
  docker/Dockerfile.oneapi
  docker/Dockerfile.redhat
Labels: housekeeping, ci

#2665 macOS CI updates
  .github/workflows/macos.yml
Labels: ci

#2668 Bump PETSc to 3.19
  docker/Dockerfile.test-env
  python/demo/demo_lagrange_variants.py
Labels: housekeeping, ci

#2669 Reduce number of build threads for doxygen in Docker
  docker/Dockerfile.test-env
Labels: docker

#2670 Update PETSC_ARCH in CI
  .circleci/config.yml
  .github/workflows/ccpp.yml
  .github/workflows/oneapi.yml
  .github/workflows/pyvista.yml
  .github/workflows/redhat.yml
  .github/workflows/sonarcloud.yml
  docker/Dockerfile.end-user
  docker/Dockerfile.oneapi
  docker/Dockerfile.test-env
  docker/complex-kernel.json
  docker/dolfinx-complex-mode
  docker/dolfinx-real-mode
Labels: ci

#2672 Build petsc4py and SLEPc for `float` in Dockerfile
  docker/Dockerfile.test-env
Labels: docker

#2676 Linting fixes
  cpp/dolfinx/fem/utils.h
  python/demo/demo_axis/demo_axis.py
  python/demo/demo_biharmonic.py
  python/demo/demo_cahn-hilliard.py
  python/demo/demo_elasticity.py
  python/demo/demo_interpolation-io.py
  python/demo/demo_lagrange_variants.py
  python/demo/demo_mixed-poisson.py
  python/demo/demo_stokes.py
  python/demo/demo_waveguide/demo_half_loaded_waveguide.py
  python/dolfinx/__init__.py
  python/dolfinx/fem/forms.py
  python/dolfinx/fem/function.py
  python/dolfinx/la.py
  python/dolfinx/wrappers/caster_petsc.h
  python/test/unit/fem/test_assemble_cppimport.py
  python/test/unit/fem/test_assemble_domains.py
  python/test/unit/fem/test_assembler.py
  python/test/unit/fem/test_bcs.py
  python/test/unit/fem/test_custom_basix_element.py
  python/test/unit/fem/test_dofmap.py
  python/test/unit/fem/test_fem_pipeline.py
  python/test/unit/fem/test_function.py
  python/test/unit/fem/test_function_space.py
  python/test/unit/fem/test_interpolation.py
  python/test/unit/fem/test_mixed_element.py
  python/test/unit/fem/test_nonlinear_assembler.py
  python/test/unit/fem/test_symmetry.py
  python/test/unit/fem/test_vector_assemble.py
  python/test/unit/fem/test_vector_function.py
  python/test/unit/io/test_vtk.py
  python/test/unit/la/test_matrix_csr.py
  python/test/unit/mesh/test_refinement.py
Labels: housekeeping

#2678 Typos
  cpp/dolfinx/fem/utils.h
  cpp/dolfinx/graph/ordering.cpp
  cpp/dolfinx/io/ADIOS2Writers.h
  cpp/dolfinx/mesh/Topology.cpp
  cpp/dolfinx/mesh/utils.h
Labels: housekeeping

#2685 Add elasticity to 'types' demo
  python/demo/demo_types.py
  python/dolfinx/fem/assemble.py
  python/dolfinx/fem/forms.py
  python/dolfinx/fem/function.py
  python/dolfinx/la.py
  python/dolfinx/wrappers/la.cpp
  python/test/unit/fem/test_custom_assembler.py
Labels: enhancement, demo

#2683 Remove Python 'meta classes'
  cpp/dolfinx/la/MatrixCSR.h
  python/demo/demo_biharmonic.py
  python/demo/demo_poisson.py
  python/demo/demo_static-condensation.py
  python/dolfinx/fem/__init__.py
  python/dolfinx/fem/assemble.py
  python/dolfinx/fem/bcs.py
  python/dolfinx/fem/forms.py
  python/dolfinx/fem/function.py
  python/dolfinx/fem/petsc.py
  python/dolfinx/la.py
  python/test/unit/fem/test_assemble_cppimport.py
  python/test/unit/fem/test_assembler.py
  python/test/unit/fem/test_bcs.py
  python/test/unit/fem/test_custom_jit_kernels.py
  python/test/unit/la/test_matrix_csr.py
Labels: enhancement, documentation, type-hints

#2684 Expose lower level `insert_diagonal` function
  cpp/dolfinx/la/MatrixCSR.h
  cpp/dolfinx/la/matrix_csr_impl.h
  python/dolfinx/fem/__init__.py
  python/dolfinx/wrappers/assemble.cpp
  python/dolfinx/wrappers/common.cpp
  python/test/unit/la/test_matrix_csr.py
Labels: enhancement

#2688 Consolidate petsc wrapper code into one file
  python/CMakeLists.txt
  python/dolfinx/wrappers/assemble.cpp
  python/dolfinx/wrappers/dolfinx.cpp
  python/dolfinx/wrappers/fem.cpp
  python/dolfinx/wrappers/la.cpp
  python/dolfinx/wrappers/nls.cpp
  python/dolfinx/wrappers/petsc.cpp
  python/dolfinx/wrappers/pycoeff.h
Labels: housekeeping

#2691 CI using float with oneAPI
  .github/workflows/oneapi.yml
  cpp/dolfinx/geometry/gjk.h
Labels: ci

#2692 Remove petsc4py from tests where possible
  python/dolfinx/la.py
  python/test/unit/fem/test_assemble_domains.py
  python/test/unit/fem/test_custom_jit_kernels.py
  python/test/unit/fem/test_expression.py
  python/test/unit/fem/test_function.py
  python/test/unit/fem/test_mixed_element.py
  python/test/unit/la/test_vector_scatter.py
Labels: testing, ci

#2694 oneAPI test improvements
  .github/workflows/oneapi.yml
  python/test/unit/io/test_xdmf_mesh.py
  python/test/unit/mesh/test_mesh.py
Labels: testing, ci

#2690 Constrain scalar types with concept
  cpp/dolfinx/common/MPI.h
  cpp/dolfinx/common/math.h
  cpp/dolfinx/common/types.h
  cpp/dolfinx/fem/Constant.h
  cpp/dolfinx/fem/DirichletBC.h
  cpp/dolfinx/fem/Expression.h
  cpp/dolfinx/fem/Form.h
  cpp/dolfinx/fem/Function.h
  cpp/dolfinx/fem/FunctionSpace.h
  cpp/dolfinx/fem/assemble_matrix_impl.h
  cpp/dolfinx/fem/assemble_scalar_impl.h
  cpp/dolfinx/fem/assemble_vector_impl.h
  cpp/dolfinx/fem/assembler.h
  cpp/dolfinx/fem/discreteoperators.h
  cpp/dolfinx/fem/interpolate.h
  cpp/dolfinx/fem/petsc.h
  cpp/dolfinx/fem/utils.h
  cpp/dolfinx/geometry/BoundingBoxTree.h
  cpp/dolfinx/graph/ordering.h
  cpp/dolfinx/io/ADIOS2Writers.h
  cpp/dolfinx/io/VTKFile.cpp
  cpp/dolfinx/io/VTKFile.h
  cpp/dolfinx/io/XDMFFile.cpp
  cpp/dolfinx/io/XDMFFile.h
  cpp/dolfinx/io/xdmf_function.cpp
  cpp/dolfinx/io/xdmf_function.h
  cpp/dolfinx/io/xdmf_utils.cpp
  cpp/dolfinx/io/xdmf_utils.h
  cpp/dolfinx/mesh/Geometry.h
  cpp/dolfinx/mesh/generation.h
  cpp/dolfinx/mesh/utils.h
  cpp/dolfinx/refinement/plaza.h
  cpp/dolfinx/refinement/refine.h
  cpp/dolfinx/refinement/utils.h
Labels: enhancement

#2696 Reduce code duplication
  cpp/dolfinx/geometry/BoundingBoxTree.h
  cpp/dolfinx/io/VTKFile.cpp
  cpp/dolfinx/io/VTKFile.h
  cpp/dolfinx/io/XDMFFile.cpp
  cpp/dolfinx/io/XDMFFile.h
  cpp/dolfinx/io/xdmf_function.cpp
  cpp/dolfinx/io/xdmf_function.h
  cpp/dolfinx/io/xdmf_meshtags.h
  cpp/dolfinx/mesh/Mesh.h
  python/dolfinx/wrappers/io.cpp
Labels: housekeeping

#2698 Disable a nested matrix test in single precision
  python/test/unit/fem/test_nonlinear_assembler.py
Labels: ci

#2695 Remove more petsc-specific tests
  python/dolfinx/wrappers/assemble.cpp
  python/test/unit/fem/test_assemble_cppimport.py
  python/test/unit/fem/test_discrete_operators.py
  python/test/unit/fem/test_element_integrals.py
  python/test/unit/fem/test_function.py
  python/test/unit/fem/test_petsc_discrete_operators.py
  python/test/unit/fem/test_symmetry.py
  python/test/unit/io/test_adios2.py
Labels: testing, ci

#2699 Add interface to wrap MatrixCSR as SciPy sparse matrix
  python/dolfinx/fem/function.py
  python/dolfinx/la.py
  python/test/unit/fem/test_bcs.py
  python/test/unit/fem/test_expression.py
  python/test/unit/la/test_matrix_csr.py
Labels: enhancement
