Repository FEniCS/dolfinx, pull requests merged in 2023-09, with the labels that each got.

#2753 Fix LaTeX text formatting issue
  python/demo/demo_biharmonic.py
  python/demo/demo_cahn-hilliard.py
  python/demo/demo_pml/demo_pml.py
  python/demo/demo_pml/efficiencies_pml_demo.py
  python/demo/demo_poisson.py
  python/demo/demo_scattering_boundary_conditions/analytical_efficiencies_wire.py
  python/demo/demo_scattering_boundary_conditions/demo_scattering_boundary_conditions.py
  python/demo/demo_waveguide/demo_half_loaded_waveguide.py
Labels: bug, documentation

#2766 Add shape argument to `FunctionSpace` for creating blocked scalar element spaces
  .github/workflows/ccpp.yml
  python/demo/demo_axis/demo_axis.py
  python/demo/demo_biharmonic.py
  python/demo/demo_cahn-hilliard.py
  python/demo/demo_elasticity.py
  python/demo/demo_helmholtz.py
  python/demo/demo_interpolation-io.py
  python/demo/demo_lagrange_variants.py
  python/demo/demo_mixed-poisson.py
  python/demo/demo_navier-stokes.py
  python/demo/demo_pml/demo_pml.py
  python/demo/demo_poisson.py
  python/demo/demo_pyvista.py
  python/demo/demo_scattering_boundary_conditions/demo_scattering_boundary_conditions.py
  python/demo/demo_static-condensation.py
  python/demo/demo_stokes.py
  python/demo/demo_tnt-elements.py
  python/demo/demo_types.py
  python/demo/demo_waveguide/demo_half_loaded_waveguide.py
  python/dolfinx/fem/__init__.py
  python/dolfinx/fem/assemble.py
  python/dolfinx/fem/bcs.py
  python/dolfinx/fem/forms.py
  python/dolfinx/fem/function.py
  python/dolfinx/jit.py
  python/dolfinx/mesh.py
  python/dolfinx/plot.py
  python/test/unit/fem/test_assemble_cppimport.py
  python/test/unit/fem/test_assembler.py
  python/test/unit/fem/test_bcs.py
  python/test/unit/fem/test_dof_permuting.py
  python/test/unit/fem/test_dofmap.py
  python/test/unit/fem/test_element_integrals.py
  python/test/unit/fem/test_expression.py
  python/test/unit/fem/test_fem_pipeline.py
  python/test/unit/fem/test_function.py
  python/test/unit/fem/test_function_space.py
  python/test/unit/fem/test_interpolation.py
  python/test/unit/fem/test_mixed_element.py
  python/test/unit/fem/test_nonlinear_assembler.py
  python/test/unit/fem/test_petsc_discrete_operators.py
  python/test/unit/fem/test_vector_assemble.py
  python/test/unit/io/test_adios2.py
  python/test/unit/io/test_vtk.py
  python/test/unit/io/test_xdmf_function.py
  python/test/unit/la/test_krylov_solver.py
  python/test/unit/la/test_nullspace.py
  python/test/unit/la/test_sparsity_pattern.py
Labels: enhancement, documentation

#2763 Remove "create" prefix from some functions
  python/demo/demo_axis/demo_axis.py
  python/demo/demo_biharmonic.py
  python/demo/demo_cahn-hilliard.py
  python/demo/demo_interpolation-io.py
  python/demo/demo_pml/demo_pml.py
  python/demo/demo_poisson.py
  python/demo/demo_pyvista.py
  python/demo/demo_scattering_boundary_conditions/demo_scattering_boundary_conditions.py
  python/demo/demo_types.py
  python/demo/demo_waveguide/demo_half_loaded_waveguide.py
  python/dolfinx/fem/function.py
  python/dolfinx/graph.py
  python/dolfinx/plot.py
  python/test/unit/fem/test_assembler.py
  python/test/unit/graph/test_adjacencylist.py
  python/test/unit/io/test_adios2.py
  python/test/unit/io/test_vtk.py
  python/test/unit/mesh/test_mesh.py
  python/test/unit/mesh/test_meshtags.py
Labels: housekeeping

#2770 Create doc images in doc source rather than code source directory
  python/doc/source/jupytext_process.py
Labels: documentation, housekeeping

#2777 Stop using deprecated UFL initialisation
  python/test/unit/fem/test_expression.py
Labels: housekeeping

#2778 Add missing templating of inverse transform
  python/dolfinx/wrappers/fem.cpp
Labels: bug

#2775 Re-design gmsh import in `io.gmshio`
  python/doc/source/api.rst
  python/dolfinx/io/gmshio.py
  python/dolfinx/mesh.py
Labels: documentation, housekeeping

#2779 Update Github action versions
  .github/workflows/build-wheels.yml
  .github/workflows/ccpp.yml
  .github/workflows/docker-dev-test-env.yml
  .github/workflows/docker-end-user.yml
  .github/workflows/docker-oneapi-test-env.yml
  .github/workflows/docker-redhat-test-env.yml
  .github/workflows/macos.yml
  .github/workflows/oneapi.yml
  .github/workflows/pyvista.yml
  .github/workflows/redhat.yml
  .github/workflows/sonarcloud.yml
  .github/workflows/spack.yml
Labels: housekeeping, ci

#2780 Revise a `gmshio` docstring
  python/dolfinx/io/gmshio.py
Labels: documentation

#2782 Change release/development order in spack test
  .github/workflows/spack.yml
Labels: ci

#2783 Add complex wrappers for equivalent floating type for exposed dof transformations
  python/dolfinx/wrappers/fem.cpp
Labels: enhancement

#2790 Bump dependency versions in Dockerfiles
  docker/Dockerfile.end-user
  docker/Dockerfile.oneapi
  docker/Dockerfile.redhat
  docker/Dockerfile.test-env
Labels: docker

#2791 PETSc version updates
  .github/workflows/ccpp.yml
  .github/workflows/docker-oneapi-test-env.yml
  .github/workflows/oneapi.yml
  .github/workflows/pyvista.yml
  docker/Dockerfile.oneapi
  docker/Dockerfile.redhat
  docker/Dockerfile.test-env
Labels: docker, ci
