Repository FEniCS/dolfinx, pull requests merged in 2023-05, with the labels that each got.

#2644 Use more expressive Actions labels
  .github/workflows/ccpp.yml
Labels: housekeeping, ci

#2643 Remove "needs" from the first step of the end-user Docker images workflow, since now build images are prepared in a standalone workflow
  .github/workflows/docker-end-user.yml
  README.md
Labels: docker, ci

#2646 Fix over-elaborated enum int type
  cpp/dolfinx/common/timing.h
Labels: bug

#2648 Fix macOS CI
  .github/workflows/macos.yml
  python/CMakeLists.txt
Labels: ci

#2657 Remove petsc from some tests
  python/dolfinx/wrappers/common.cpp
  python/dolfinx/wrappers/io.cpp
  python/dolfinx/wrappers/mesh.cpp
  python/test/unit/io/test_xdmf_function.py
  python/test/unit/mesh/test_refinement.py
Labels: housekeeping, ci

#2654 Add Block support to MatrixCSR
  cpp/dolfinx/la/CMakeLists.txt
  cpp/dolfinx/la/MatrixCSR.h
  cpp/dolfinx/la/matrix_csr_impl.h
  python/dolfinx/la.py
  python/dolfinx/wrappers/assemble.cpp
  python/dolfinx/wrappers/la.cpp
  python/test/unit/fem/test_assemble_cppimport.py
  python/test/unit/fem/test_assembler.py
  python/test/unit/fem/test_vector_assemble.py
  python/test/unit/la/test_matrix_csr.py
Labels: enhancement

#2660 Wrong function-space used in direct solver
  python/demo/demo_stokes.py
Labels: bug
