Repository FEniCS/dolfinx, pull requests merged in 2023-10, with the labels that each got.

#2810 TST: add missing include <functional>
  cpp/test/common/sort.cpp
Labels: bug

#2808 Missing from __future__ import annotations
  python/dolfinx/mesh.py
Labels: bug

#2818 Remove deprecated `fem.FunctionSpace` function
  python/demo/demo_biharmonic.py
  python/demo/demo_cahn-hilliard.py
  python/demo/demo_elasticity.py
  python/demo/demo_poisson.py
  python/demo/demo_stokes.py
  python/demo/demo_tnt-elements.py
  python/dolfinx/fem/__init__.py
  python/dolfinx/fem/bcs.py
  python/dolfinx/fem/forms.py
  python/dolfinx/fem/function.py
  python/dolfinx/mesh.py
  python/dolfinx/plot.py
  python/test/unit/fem/test_assemble_cppimport.py
  python/test/unit/fem/test_assemble_domains.py
  python/test/unit/fem/test_assemble_submesh.py
  python/test/unit/fem/test_assembler.py
  python/test/unit/fem/test_bcs.py
  python/test/unit/fem/test_complex_assembler.py
  python/test/unit/fem/test_custom_assembler.py
  python/test/unit/fem/test_custom_basix_element.py
  python/test/unit/fem/test_custom_jit_kernels.py
  python/test/unit/fem/test_discrete_operators.py
  python/test/unit/fem/test_dof_coordinates.py
  python/test/unit/fem/test_dof_permuting.py
  python/test/unit/fem/test_dofmap.py
  python/test/unit/fem/test_element_integrals.py
  python/test/unit/fem/test_expression.py
  python/test/unit/fem/test_fem_pipeline.py
  python/test/unit/fem/test_forms.py
  python/test/unit/fem/test_function.py
  python/test/unit/fem/test_function_space.py
  python/test/unit/fem/test_ghost_mesh_assembly.py
  python/test/unit/fem/test_interpolation.py
  python/test/unit/fem/test_mixed_element.py
  python/test/unit/fem/test_nonlinear_assembler.py
  python/test/unit/fem/test_petsc_discrete_operators.py
  python/test/unit/fem/test_symmetry.py
  python/test/unit/fem/test_vector_assemble.py
  python/test/unit/fem/test_vector_function.py
  python/test/unit/io/test_adios2.py
  python/test/unit/io/test_vtk.py
  python/test/unit/io/test_xdmf_function.py
  python/test/unit/la/test_krylov_solver.py
  python/test/unit/la/test_matrix_csr.py
  python/test/unit/la/test_matrix_vector.py
  python/test/unit/la/test_nullspace.py
  python/test/unit/la/test_sparsity_pattern.py
  python/test/unit/la/test_vector_scatter.py
  python/test/unit/mesh/test_refinement.py
  python/test/unit/nls/test_newton.py
Labels: housekeeping

#2823 Fix redhat dockerfile
  docker/Dockerfile.redhat
Labels: ci

#2824 Fix conda CI tests
  .github/workflows/conda.yml
Labels: ci

#2833 Remove unnecessary `py.typed` markers in python subpackages
  python/dolfinx/fem/py.typed
  python/dolfinx/nls/py.typed
  python/setup.py
Labels: housekeeping

#2836 Drop setting dl open flags in `dolfinx/__init__.py`
  docker/Dockerfile.redhat
  docker/Dockerfile.test-env
  python/dolfinx/__init__.py
Labels: housekeeping

#2822 Improve documentation of `pack_coefficients`
  cpp/dolfinx/fem/utils.h
Labels: documentation

#2839 Doc string improvement
  cpp/dolfinx/fem/utils.h
Labels: documentation, housekeeping

#2707 Use `pyproject.toml` for install of Python part
  .circleci/config.yml
  .github/workflows/ccpp.yml
  .github/workflows/macos.yml
  .github/workflows/oneapi.yml
  .github/workflows/redhat.yml
  docker/Dockerfile.end-user
  docker/Dockerfile.oneapi
  docker/Dockerfile.redhat
  docker/Dockerfile.test-env
  python/.flake8
  python/CMakeLists.txt
  python/README.rst
  python/build-requirements.txt
  python/demo/conftest.py
  python/pyproject.toml
  python/setup.cfg
  python/setup.py
Labels: build, install

#2838 Add `flake8` and `isort` checks on python files in `cpp` folder
  .flake8
  .github/workflows/ccpp.yml
  cpp/demo/hyperelasticity/hyperelasticity.py
  cpp/demo/poisson_matrix_free/poisson.py
  cpp/test/poisson.py
Labels: housekeeping

#2842 Remove unused pylit3 fron doc dependencies
  python/pyproject.toml
Labels: housekeeping
