Repository FEniCS/dolfinx, pull requests merged in 2023-11, with the labels that each got.

#2848 Update computation of number of components for arbitrary value shape in `xdmf_function`
  cpp/dolfinx/io/xdmf_function.cpp
Labels: bug

#2856 Remove unnecessary calls to `compute_graph_edges`
  cpp/dolfinx/common/IndexMap.cpp
Labels: performance

#2857 Move upgrade of pip/setuptools from redhat workflow to redhat docker file, and remove installation of build requirements from workflows
  .github/workflows/ccpp.yml
  .github/workflows/oneapi.yml
  .github/workflows/redhat.yml
  docker/Dockerfile.redhat
Labels: docker, ci

#2865 Fix CI build with OpenMPI5: remove some env variables
  .github/workflows/ccpp.yml
Labels: ci

#2862 Improve collision detection
  cpp/dolfinx/geometry/utils.h
Labels: performance, backport?

#2866 Fix `pyvista` demo and workflow
  .github/workflows/pyvista.yml
  python/demo/demo_pyvista.py
Labels: ci

#2863 Bump versions in Dockerfiles
  docker/Dockerfile.end-user
  docker/Dockerfile.oneapi
  docker/Dockerfile.redhat
  docker/Dockerfile.test-env
Labels: docker, ci

#2875 Remove call to `compute_graph_edges` in `compute_owned_indices`
  cpp/dolfinx/common/IndexMap.cpp
  cpp/dolfinx/common/IndexMap.h
  cpp/dolfinx/mesh/Geometry.h
  cpp/dolfinx/mesh/Topology.cpp
Labels: performance

#2883 Change python/README to markdown
  python/README.md
  python/README.rst
Labels: housekeeping

#2858 Speed up non-matching interpolation data and add extrapolation parameter
  cpp/demo/interpolation_different_meshes/main.cpp
  cpp/dolfinx/fem/interpolate.h
  cpp/dolfinx/geometry/utils.h
  python/dolfinx/wrappers/fem.cpp
  python/dolfinx/wrappers/geometry.cpp
  python/test/unit/fem/test_interpolation.py
Labels: performance, backport?

#2803 Let PETSc choose default LU solver within NewtonSolver
  cpp/dolfinx/nls/NewtonSolver.cpp
  python/demo/demo_cahn-hilliard.py
Labels: enhancement

#2895 Change nanobind build options to remove `-Os`
  python/CMakeLists.txt
Labels: performance, build

#2894 Correct CMAKE_BUILD_TYPE in end user Docker images
  .github/workflows/docker-end-user.yml
  docker/Dockerfile.end-user
Labels: performance, high-priority, docker

#2896 Simplify CMake for Python interface build
  python/CMakeLists.txt
Labels: build, housekeeping

#2899 Work-around nanobind issue with `std::function`
  cpp/dolfinx/nls/NewtonSolver.cpp
  cpp/dolfinx/nls/NewtonSolver.h
  python/dolfinx/wrappers/petsc.cpp
  python/test/unit/nls/test_newton.py
Labels: nanobind

#2909 Add `ruff` to base test environment
  docker/Dockerfile.test-env
Labels: docker, ci

#2915 Fix broken links to integration test workflows in `RELEASE.md`
  RELEASE.md
Labels: housekeeping

#2912 Update GH bug template
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: housekeeping

#2914 Fix misleading commit message when updating documentation repository
  .github/workflows/ccpp.yml
Labels: documentation, ci
