Repository FEniCS/dolfinx, pull requests merged in 2023-07, with the labels that each got.

#2708 Fix extraction of `fem::Function` names in ADIOS2-based output
  cpp/demo/poisson/main.cpp
  cpp/dolfinx/io/ADIOS2Writers.cpp
  cpp/dolfinx/io/ADIOS2Writers.h
  python/dolfinx/io/utils.py
  python/setup.cfg
Labels: bug, io

#2703 Isolate petsc4y in Python interface
  cpp/dolfinx/la/MatrixCSR.h
  cpp/dolfinx/la/Vector.h
  cpp/dolfinx/la/petsc.cpp
  python/demo/demo_axis/demo_axis.py
  python/demo/demo_biharmonic.py
  python/demo/demo_elasticity.py
  python/demo/demo_lagrange_variants.py
  python/demo/demo_mixed-poisson.py
  python/demo/demo_navier_stokes.py
  python/demo/demo_pml/demo_pml.py
  python/demo/demo_poisson.py
  python/demo/demo_scattering_boundary_conditions/demo_scattering_boundary_conditions.py
  python/demo/demo_stokes.py
  python/demo/demo_tnt-elements.py
  python/demo/demo_types.py
  python/demo/demo_waveguide/demo_half_loaded_waveguide.py
  python/dolfinx/__init__.py
  python/dolfinx/common.py
  python/dolfinx/fem/__init__.py
  python/dolfinx/fem/assemble.py
  python/dolfinx/fem/function.py
  python/dolfinx/fem/petsc.py
  python/dolfinx/geometry.py
  python/dolfinx/graph.py
  python/dolfinx/io/utils.py
  python/dolfinx/jit.py
  python/dolfinx/la.py
  python/dolfinx/log.py
  python/dolfinx/mesh.py
  python/dolfinx/nls/__init__.py
  python/dolfinx/nls/petsc.py
  python/dolfinx/pkgconfig.py
  python/dolfinx/plot.py
  python/dolfinx/wrappers/common.cpp
  python/dolfinx/wrappers/la.cpp
  python/dolfinx/wrappers/petsc.cpp
  python/test/unit/fem/test_assembler.py
  python/test/unit/io/test_xdmf_function.py
  python/test/unit/la/test_nullspace.py
  python/test/unit/nls/test_newton.py
Labels: bug, enhancement, documentation, housekeeping

#2709 Pass ADIOS2 egine through for Fides (Python)
  python/demo/demo_navier-stokes.py
  python/doc/Makefile
  python/doc/source/demos.rst
  python/dolfinx/geometry.py
  python/dolfinx/io/__init__.py
  python/dolfinx/io/utils.py
  python/dolfinx/wrappers/io.cpp
Labels: bug, io

#2697 Make numerical tolerance dependent on input type
  cpp/dolfinx/fem/discreteoperators.h
  cpp/dolfinx/geometry/gjk.h
  cpp/dolfinx/geometry/utils.h
Labels: bug

#2721 Add optional type check in HDF5 files
  cpp/CMakeLists.txt
  cpp/dolfinx/CMakeLists.txt
  cpp/dolfinx/io/CMakeLists.txt
  cpp/dolfinx/io/HDF5Interface.cpp
  cpp/dolfinx/io/HDF5Interface.h
  cpp/dolfinx/io/XDMFFile.cpp
  cpp/dolfinx/io/xdmf_function.cpp
  cpp/dolfinx/io/xdmf_mesh.cpp
  cpp/dolfinx/io/xdmf_mesh.h
  cpp/dolfinx/io/xdmf_meshtags.h
  cpp/dolfinx/io/xdmf_read.h
  cpp/dolfinx/io/xdmf_utils.h
Labels: proposal

#2722 Add missing forward scatters in C++ demos
  cpp/demo/biharmonic/main.cpp
  cpp/demo/poisson/main.cpp
Labels: bug, demo

#2725 Avoid introducing HDF5-HL library
  cpp/CMakeLists.txt
  cpp/dolfinx/CMakeLists.txt
  cpp/dolfinx/io/HDF5Interface.h
Labels: housekeeping

#2726 Dependency version bumps in Dockerfiles
  docker/Dockerfile.oneapi
  docker/Dockerfile.redhat
  docker/Dockerfile.test-env
Labels: docker

#2731 Use PETSc release version in oneAPI docker file
  .github/workflows/docker-oneapi-test-env.yml
  docker/Dockerfile.oneapi
  python/test/unit/fem/test_vector_function.py
Labels: docker, ci

#2730 Simplify `fem::Expression`
  cpp/demo/hyperelasticity/main.cpp
  cpp/dolfinx/fem/Expression.h
  cpp/dolfinx/fem/Function.h
  cpp/dolfinx/fem/utils.h
  python/demo/demo_pyvista.py
  python/dolfinx/fem/forms.py
  python/dolfinx/fem/function.py
  python/dolfinx/fem/petsc.py
  python/dolfinx/io/gmshio.py
  python/dolfinx/jit.py
  python/dolfinx/wrappers/fem.cpp
  python/test/unit/fem/test_expression.py
  python/test/unit/mesh/test_ghost_mesh.py
Labels: bug, housekeeping

#2727 Allow trivial (null) cell partitioner
  cpp/dolfinx/graph/AdjacencyList.h
  cpp/dolfinx/graph/partition.h
  cpp/dolfinx/mesh/Topology.h
  cpp/dolfinx/mesh/generation.h
  cpp/dolfinx/mesh/topologycomputation.h
  cpp/dolfinx/mesh/utils.h
  python/dolfinx/mesh.py
  python/dolfinx/wrappers/mesh.cpp
Labels: performance

#2732 Rename ‘MatrixCSR::finalize’ to ‘MatrixCSR::scatter_rev’
  cpp/dolfinx/la/MatrixCSR.h
  cpp/test/matrix.cpp
  python/demo/demo_types.py
  python/dolfinx/la.py
  python/dolfinx/wrappers/la.cpp
  python/test/unit/fem/test_assemble_cppimport.py
  python/test/unit/fem/test_assemble_domains.py
  python/test/unit/fem/test_assemble_submesh.py
  python/test/unit/fem/test_assembler.py
  python/test/unit/fem/test_bcs.py
  python/test/unit/fem/test_custom_jit_kernels.py
  python/test/unit/fem/test_discrete_operators.py
  python/test/unit/fem/test_element_integrals.py
  python/test/unit/fem/test_expression.py
  python/test/unit/fem/test_ghost_mesh_assembly.py
  python/test/unit/fem/test_mixed_element.py
  python/test/unit/fem/test_symmetry.py
  python/test/unit/fem/test_vector_assemble.py
  python/test/unit/la/test_matrix_csr.py
Labels: housekeeping

#2733 Update to Catch2 v3 for C++ unit testing
  cpp/test/CMakeLists.txt
  cpp/test/common/CIFailure.cpp
  cpp/test/common/index_map.cpp
  cpp/test/common/sort.cpp
  cpp/test/common/sub_systems_manager.cpp
  cpp/test/io.cpp
  cpp/test/main.cpp
  cpp/test/matrix.cpp
  cpp/test/mesh/distributed_mesh.cpp
  cpp/test/vector.cpp
Labels: testing

#2734 Refactor Gmsh demo
  python/demo/demo_elasticity.py
  python/demo/demo_gmsh.py
  python/demo/demo_tnt-elements.py
  python/dolfinx/io/gmshio.py
Labels: demo

#2735 Require interpolation before XDMF output
  cpp/demo/hyperelasticity/main.cpp
  cpp/demo/interpolation-io/main.cpp
  cpp/demo/interpolation_different_meshes/main.cpp
  cpp/dolfinx/fem/FiniteElement.cpp
  cpp/dolfinx/fem/FiniteElement.h
  cpp/dolfinx/fem/utils.h
  cpp/dolfinx/io/ADIOS2Writers.h
  cpp/dolfinx/io/VTKFile.cpp
  cpp/dolfinx/io/VTKFile.h
  cpp/dolfinx/io/XDMFFile.h
  cpp/dolfinx/io/vtk_utils.h
  cpp/dolfinx/io/xdmf_function.cpp
  cpp/dolfinx/io/xdmf_mesh.cpp
  cpp/dolfinx/io/xdmf_utils.cpp
  cpp/dolfinx/io/xdmf_utils.h
  cpp/test/io.cpp
  python/demo/demo_biharmonic.py
  python/demo/demo_interpolation-io.py
  python/demo/demo_stokes.py
  python/dolfinx/io/gmshio.py
  python/dolfinx/mesh.py
  python/test/unit/io/test_vtk.py
  python/test/unit/io/test_xdmf_function.py
  python/test/unit/io/test_xdmf_mesh.py
Labels: bug, enhancement, io
