Repository FEniCS/dolfinx, pull requests merged in 2023-04, with the labels that each got.

#2610 Add default scalar type
  python/demo/demo_biharmonic.py
  python/demo/demo_elasticity.py
  python/demo/demo_interpolation-io.py
  python/demo/demo_lagrange_variants.py
  python/dolfinx/__init__.py
  python/dolfinx/fem/forms.py
  python/dolfinx/fem/function.py
  python/test/unit/fem/test_assemble_domains.py
Labels: housekeeping

#2615 Remove inconsistent behaviour when building sparsity pattern from forms
  cpp/dolfinx/fem/petsc.h
Labels: bug, enhancement

#2617 Simplify `fem::Form` domain handling
  cpp/dolfinx/fem/Form.h
  cpp/dolfinx/fem/assemble_matrix_impl.h
  cpp/dolfinx/fem/assemble_scalar_impl.h
  cpp/dolfinx/fem/assemble_vector_impl.h
  cpp/dolfinx/fem/utils.h
  python/dolfinx/wrappers/fem.cpp
Labels: housekeeping

#2623 Update for Basix type changes
  cpp/dolfinx/fem/FiniteElement.cpp
Labels: housekeeping

#2626 Fix std::function memory error in Forms
  cpp/dolfinx/fem/Form.h
  cpp/dolfinx/fem/assemble_matrix_impl.h
  cpp/dolfinx/fem/assemble_scalar_impl.h
  cpp/dolfinx/fem/assemble_vector_impl.h
Labels: bug

#2635 Add `complex` to type hints for `Constant`
  python/dolfinx/fem/function.py
Labels: type-hints

#2636 Add ADIOS2 engine as option
  cpp/demo/interpolation-io/main.cpp
  cpp/dolfinx/io/ADIOS2Writers.cpp
  cpp/dolfinx/io/ADIOS2Writers.h
  cpp/dolfinx/refinement/plaza.h
  cpp/dolfinx/refinement/utils.h
  python/dolfinx/wrappers/io.cpp
Labels: enhancement

#2632 Flatten dofmap storage
  cpp/dolfinx/fem/DirichletBC.cpp
  cpp/dolfinx/fem/DofMap.cpp
  cpp/dolfinx/fem/DofMap.h
  cpp/dolfinx/fem/Expression.h
  cpp/dolfinx/fem/Function.h
  cpp/dolfinx/fem/FunctionSpace.h
  cpp/dolfinx/fem/assemble_matrix_impl.h
  cpp/dolfinx/fem/assemble_scalar_impl.h
  cpp/dolfinx/fem/assemble_vector_impl.h
  cpp/dolfinx/fem/discreteoperators.h
  cpp/dolfinx/fem/dofmapbuilder.cpp
  cpp/dolfinx/fem/dofmapbuilder.h
  cpp/dolfinx/fem/interpolate.h
  cpp/dolfinx/fem/utils.cpp
  cpp/dolfinx/geometry/utils.h
  cpp/dolfinx/graph/partition.cpp
  cpp/dolfinx/graph/partition.h
  cpp/dolfinx/io/ADIOS2Writers.h
  cpp/dolfinx/io/vtk_utils.cpp
  cpp/dolfinx/io/vtk_utils.h
  cpp/dolfinx/io/xdmf_mesh.cpp
  cpp/dolfinx/io/xdmf_utils.cpp
  cpp/dolfinx/mesh/Geometry.h
  cpp/dolfinx/mesh/utils.h
  cpp/dolfinx/refinement/plaza.h
  cpp/dolfinx/refinement/utils.h
  python/demo/demo_elasticity.py
  python/dolfinx/fem/dofmap.py
  python/dolfinx/plot.py
  python/dolfinx/wrappers/fem.cpp
  python/dolfinx/wrappers/geometry.cpp
  python/dolfinx/wrappers/io.cpp
  python/dolfinx/wrappers/mesh.cpp
  python/test/unit/fem/test_custom_assembler.py
  python/test/unit/fem/test_dof_permuting.py
  python/test/unit/fem/test_dofmap.py
  python/test/unit/fem/test_element_integrals.py
  python/test/unit/fem/test_expression.py
  python/test/unit/la/test_nullspace.py
  python/test/unit/mesh/test_mesh.py
Labels: enhancement

#2634 Support for `FiniteElement`s with different scalar types
  cpp/demo/interpolation-io/main.cpp
  cpp/demo/mixed_topology/main.cpp
  cpp/dolfinx/fem/CoordinateElement.cpp
  cpp/dolfinx/fem/CoordinateElement.h
  cpp/dolfinx/fem/Expression.h
  cpp/dolfinx/fem/FiniteElement.cpp
  cpp/dolfinx/fem/FiniteElement.h
  cpp/dolfinx/fem/Form.h
  cpp/dolfinx/fem/Function.h
  cpp/dolfinx/fem/FunctionSpace.h
  cpp/dolfinx/fem/assemble_matrix_impl.h
  cpp/dolfinx/fem/assemble_scalar_impl.h
  cpp/dolfinx/fem/assemble_vector_impl.h
  cpp/dolfinx/fem/assembler.h
  cpp/dolfinx/fem/discreteoperators.h
  cpp/dolfinx/fem/interpolate.h
  cpp/dolfinx/fem/utils.cpp
  cpp/dolfinx/fem/utils.h
  cpp/dolfinx/geometry/utils.h
  cpp/dolfinx/graph/AdjacencyList.h
  cpp/dolfinx/io/ADIOS2Writers.h
  cpp/dolfinx/io/XDMFFile.cpp
  cpp/dolfinx/io/XDMFFile.h
  cpp/dolfinx/io/vtk_utils.h
  cpp/dolfinx/io/xdmf_function.cpp
  cpp/dolfinx/io/xdmf_utils.cpp
  cpp/dolfinx/io/xdmf_utils.h
  cpp/dolfinx/la/MatrixCSR.h
  cpp/dolfinx/mesh/Geometry.h
  cpp/dolfinx/mesh/Mesh.h
  cpp/dolfinx/mesh/generation.h
  cpp/dolfinx/mesh/permutationcomputation.cpp
  cpp/dolfinx/mesh/topologycomputation.cpp
  cpp/dolfinx/mesh/utils.h
  cpp/test/io.cpp
  cpp/test/mesh/distributed_mesh.cpp
  cpp/test/vector.cpp
  python/dolfinx/io/utils.py
  python/dolfinx/mesh.py
  python/dolfinx/wrappers/assemble.cpp
  python/dolfinx/wrappers/fem.cpp
  python/dolfinx/wrappers/mesh.cpp
  python/test/unit/mesh/test_mesh.py
Labels: enhancement

#2640 Fix for interpolation of a callable on cells subset
  cpp/dolfinx/fem/interpolate.h
  python/test/unit/fem/test_interpolation.py
Labels: bug
