Repository FEniCS/dolfinx, pull requests merged in 2023-02, with the labels that each got.

#2522 Wrap mesh tags from Python
  cpp/dolfinx/fem/Form.h
  cpp/dolfinx/fem/utils.h
  cpp/dolfinx/io/VTKFile.cpp
  cpp/dolfinx/io/XDMFFile.h
  cpp/dolfinx/refinement/utils.cpp
  cpp/dolfinx/refinement/utils.h
  python/demo/demo_axis/demo_axis.py
  python/demo/demo_static-condensation.py
  python/dolfinx/fem/forms.py
  python/dolfinx/geometry.py
  python/dolfinx/io/utils.py
  python/dolfinx/mesh.py
  python/dolfinx/wrappers/fem.cpp
  python/dolfinx/wrappers/io.cpp
  python/dolfinx/wrappers/refinement.cpp
  python/test/unit/common/test_public_api.py
  python/test/unit/fem/test_constant.py
  python/test/unit/fem/test_custom_jit_kernels.py
  python/test/unit/fem/test_element_integrals.py
  python/test/unit/io/test_xdmf_meshtags.py
  python/test/unit/mesh/test_mesh_partitioners.py
  python/test/unit/mesh/test_meshtags.py
  python/test/unit/mesh/test_refinement.py
Labels: bug, enhancement

#2528 Tidy up Python wrapping of mesh refinement interface
  cpp/demo/interpolation_different_meshes/main.cpp
  cpp/dolfinx/common/CMakeLists.txt
  cpp/dolfinx/common/MPI.h
  cpp/dolfinx/common/dolfinx_common.h
  cpp/dolfinx/common/dolfinx_doc.h
  cpp/dolfinx/common/utils.h
  cpp/dolfinx/dolfinx.h
  cpp/dolfinx/fem/CMakeLists.txt
  cpp/dolfinx/fem/DofMap.cpp
  cpp/dolfinx/fem/DofMap.h
  cpp/dolfinx/fem/assemble_vector_impl.h
  cpp/dolfinx/fem/dolfinx_fem.h
  cpp/dolfinx/fem/petsc.h
  cpp/dolfinx/geometry/CMakeLists.txt
  cpp/dolfinx/geometry/dolfin_geometry.h
  cpp/dolfinx/geometry/dolfinx_geometry.h
  cpp/dolfinx/graph/CMakeLists.txt
  cpp/dolfinx/graph/dolfin_graph.h
  cpp/dolfinx/graph/dolfinx_graph.h
  cpp/dolfinx/io/CMakeLists.txt
  cpp/dolfinx/io/dolfin_io.h
  cpp/dolfinx/io/dolfinx_io.h
  cpp/dolfinx/la/CMakeLists.txt
  cpp/dolfinx/la/dolfin_la.h
  cpp/dolfinx/la/dolfinx_la.h
  cpp/dolfinx/la/petsc.h
  cpp/dolfinx/mesh/CMakeLists.txt
  cpp/dolfinx/mesh/dolfinx_mesh.h
  cpp/dolfinx/nls/CMakeLists.txt
  cpp/dolfinx/nls/dolfin_nls.h
  cpp/dolfinx/nls/dolfinx_nls.h
  cpp/dolfinx/refinement/CMakeLists.txt
  cpp/dolfinx/refinement/dolfin_refinement.h
  cpp/dolfinx/refinement/dolfinx_refinement.h
  cpp/dolfinx/refinement/plaza.cpp
  cpp/dolfinx/refinement/plaza.h
  cpp/dolfinx/refinement/refine.cpp
  cpp/dolfinx/refinement/refine.h
  python/dolfinx/mesh.py
  python/dolfinx/wrappers/refinement.cpp
  python/test/unit/mesh/test_refinement.py
Labels: performance, documentation, housekeeping

#2529 Split topology and geometry stages in `mesh::create_submesh`
  cpp/dolfinx/mesh/Geometry.cpp
  cpp/dolfinx/mesh/Geometry.h
  cpp/dolfinx/mesh/Mesh.cpp
  cpp/dolfinx/mesh/Topology.cpp
  cpp/dolfinx/mesh/Topology.h
  cpp/dolfinx/mesh/utils.cpp
  cpp/dolfinx/mesh/utils.h
  python/demo/demo_axis/demo_axis.py
  python/demo/demo_navier_stokes.py
  python/demo/demo_pml/demo_pml.py
  python/demo/demo_waveguide/demo_half_loaded_waveguide.py
  python/dolfinx/mesh.py
  python/dolfinx/wrappers/mesh.cpp
  python/test/unit/mesh/test_refinement.py
Labels: task, housekeeping

#2531 Fix `create_form` to only integrate over owned entities
  cpp/dolfinx/fem/utils.h
Labels: bug

#2538 Bump dev versions
  cpp/CMakeLists.txt
  python/setup.py
  python/test/unit/common/test_version.py
Labels: housekeeping

#2540 Fix doc error in `mesh.create_mesh` for coordinate layout.
  cpp/dolfinx/mesh/Geometry.h
  cpp/dolfinx/mesh/Mesh.h
  python/dolfinx/mesh.py
Labels: documentation

#2542 Minor install updates in `README.md`
  README.md
Labels: housekeeping

#2457 Template `mesh::Geometry` over scalar type
  cpp/demo/poisson/main.cpp
  cpp/demo/poisson_matrix_free/main.cpp
  cpp/dolfinx/fem/DirichletBC.h
  cpp/dolfinx/fem/assemble_matrix_impl.h
  cpp/dolfinx/fem/assemble_scalar_impl.h
  cpp/dolfinx/fem/assemble_vector_impl.h
  cpp/dolfinx/fem/assembler.h
  cpp/dolfinx/fem/petsc.cpp
  cpp/dolfinx/fem/petsc.h
  cpp/dolfinx/geometry/utils.cpp
  cpp/dolfinx/io/ADIOS2Writers.cpp
  cpp/dolfinx/io/VTKFile.cpp
  cpp/dolfinx/io/XDMFFile.cpp
  cpp/dolfinx/io/XDMFFile.h
  cpp/dolfinx/io/xdmf_mesh.cpp
  cpp/dolfinx/io/xdmf_mesh.h
  cpp/dolfinx/mesh/Geometry.cpp
  cpp/dolfinx/mesh/Geometry.h
  cpp/dolfinx/mesh/Mesh.cpp
  cpp/dolfinx/mesh/Mesh.h
  cpp/dolfinx/mesh/utils.cpp
  python/dolfinx/wrappers/mesh.cpp
Labels: enhancement

#2548 Fix UFL version in `setup.py`
  .github/workflows/spack.yml
  python/setup.py
Labels: housekeeping

#2549 Add point as cell type to be able to read in vertex tags
  cpp/dolfinx/mesh/cell_types.cpp
Labels: enhancement

#2550 Default to ninja when building Python/pybind11 interface
  .circleci/config.yml
  cpp/dolfinx/common/dolfinx_common.h
  cpp/dolfinx/fem/assemble_scalar_impl.h
  cpp/dolfinx/io/XDMFFile.cpp
  cpp/dolfinx/io/xdmf_mesh.cpp
  python/CMakeLists.txt
  python/setup.py
Labels: enhancement, build

#2551 Update OneAPI and Redhat Dockerfiles
  .github/workflows/redhat.yml
  docker/Dockerfile.oneapi
  docker/Dockerfile.redhat
Labels: demo, docker

#2552 Dockerfile PETSc version bump
  docker/Dockerfile
  python/test/conftest.py
Labels: testing, ci

#2554 Use larger arm Docker build runner (more memory)
  .github/workflows/docker.yml
  python/demo/demo_axis/demo_axis.py
  python/demo/demo_pml/demo_pml.py
Labels: docker

#2555 Remove clang from Dockerfile
  docker/Dockerfile
  python/demo/demo_cahn-hilliard.py
  python/demo/demo_interpolation-io.py
  python/demo/demo_navier_stokes.py
  python/demo/demo_pml/demo_pml.py
  python/demo/demo_static-condensation.py
  python/demo/demo_stokes.py
  python/demo/demo_tnt-elements.py
  python/demo/demo_types.py
  python/demo/demo_waveguide/demo_half_loaded_waveguide.py
  python/dolfinx/fem/__init__.py
  python/dolfinx/fem/forms.py
  python/dolfinx/fem/function.py
  python/dolfinx/geometry.py
  python/dolfinx/io/__init__.py
  python/dolfinx/io/gmshio.py
  python/dolfinx/io/utils.py
  python/dolfinx/mesh.py
  python/test/conftest.py
  python/test/unit/fem/test_custom_assembler.py
  python/test/unit/fem/test_custom_jit_kernels.py
  python/test/unit/fem/test_element_integrals.py
  python/test/unit/fem/test_expression.py
  python/test/unit/fem/test_interpolation.py
  python/test/unit/geometry/test_bounding_box_tree.py
  python/test/unit/io/test_xdmf_meshtags.py
  python/test/unit/mesh/test_meshtags.py
  python/test/unit/mesh/test_refinement.py
Labels: housekeeping, docker

#2547 Expose real version of inverse transform to python
  python/dolfinx/wrappers/fem.cpp
Labels: enhancement
