Repository FEniCS/dolfinx, pull requests merged in 2024-09, with the labels that each got.

#3124 Skip test if adios2 python module built without MPI.
  python/test/unit/io/test_adios2.py
Labels: testing, build, backport?

#3381 Run macos CI on pull requests
  .github/workflows/macos.yml
Labels: ci

#3361 Skip negative cell indices when packing coefficients
  cpp/dolfinx/fem/utils.h
  python/test/unit/fem/test_assemble_submesh.py
Labels: backport?

#3388 Windows CI on dispatch only
  .github/workflows/windows.yml
Labels: ci

#3373 Correct reference value size
  cpp/dolfinx/fem/interpolate.h
Labels: backport?

#3394 Bump dependency version in Dockerfiles
  .github/workflows/pyvista.yml
  docker/Dockerfile.end-user
  docker/Dockerfile.redhat
  docker/Dockerfile.test-env
  python/dolfinx/wrappers/la.cpp
  python/dolfinx/wrappers/refinement.cpp
Labels: docker

#3395 Avoid CMake Boost policy warning
  cpp/cmake/templates/DOLFINXConfig.cmake.in
Labels: build, housekeeping

#3405 Fix nanobinding for interprocess facets
  python/dolfinx/wrappers/mesh.cpp
Labels: bug, nanobind

#3402 Bumping sonar-scanner-cli and removing deprecated command
  .github/workflows/sonarcloud.yml
Labels: housekeeping

#3400 Expose geometry constructor in Python
  python/dolfinx/wrappers/mesh.cpp
Labels: nanobind

#3396 Remove std::map from scatter_values in nonmatching interpolation
  cpp/dolfinx/fem/interpolate.h
Labels: performance

#3397 Add missing docs regarding diagonal
  python/dolfinx/fem/assemble.py
  python/dolfinx/fem/petsc.py
Labels: documentation

#3403 Add Python-interface for geometry constructor and geometry class
  cpp/dolfinx/mesh/Geometry.h
  python/dolfinx/fem/element.py
  python/dolfinx/fem/function.py
  python/dolfinx/io/utils.py
  python/dolfinx/mesh.py
  python/dolfinx/wrappers/mesh.cpp
Labels: enhancement, documentation

#3406 Create topology Python wrapper
  python/dolfinx/fem/__init__.py
  python/dolfinx/fem/function.py
  python/dolfinx/mesh.py
  python/dolfinx/wrappers/mesh.cpp
  python/test/unit/fem/test_assemble_submesh.py
  python/test/unit/mesh/test_mixed_topology.py
Labels: enhancement, documentation

#3399 Save FFI module in fem form.
  python/dolfinx/fem/forms.py
Labels: enhancement

#3421 Fix Python wrapper of `distribute_entity_data`
  python/dolfinx/io/gmshio.py
  python/dolfinx/io/utils.py
  python/test/unit/mesh/test_meshtags.py
Labels: bug, high-priority

#3429 Fix argument block-size in Expressions
  cpp/dolfinx/fem/Expression.h
  python/test/unit/fem/test_expression.py
Labels: bug, high-priority, backport?

#3431 Fix integer overflow bug in sub-IndexMap extraction
  cpp/dolfinx/common/IndexMap.cpp
Labels: bug, high-priority

#3432 Fix mesh constructor again
  python/dolfinx/mesh.py
  python/test/unit/refinement/test_refinement.py
Labels: bug

#3392 Remove NBX call from sub-IndexMap creation
  cpp/dolfinx/common/IndexMap.cpp
Labels: performance

#3435 Remove deprecated method for accessing PETSc Vec in Python
  python/dolfinx/fem/function.py
Labels: housekeeping

#3439 Check for interprocess facets when assembling interior facet integrals
  cpp/dolfinx/fem/utils.cpp
  cpp/dolfinx/fem/utils.h
  cpp/dolfinx/mesh/Topology.h
  cpp/dolfinx/mesh/topologycomputation.cpp
  cpp/dolfinx/mesh/topologycomputation.h
  python/test/unit/fem/test_assemble_domains.py
Labels: enhancement

#3434 Use `std::optional` to reduce code duplication in boundary condition setting
  cpp/demo/biharmonic/main.cpp
  cpp/demo/codim_0_assembly/main.cpp
  cpp/demo/hyperelasticity/main.cpp
  cpp/demo/interpolation_different_meshes/main.cpp
  cpp/demo/poisson/main.cpp
  cpp/demo/poisson_matrix_free/main.cpp
  cpp/dolfinx/fem/DirichletBC.h
  cpp/dolfinx/fem/assemble_vector_impl.h
  cpp/dolfinx/fem/assembler.h
  cpp/dolfinx/fem/petsc.h
  python/demo/demo_elasticity.py
  python/demo/demo_poisson_matrix_free.py
  python/demo/demo_pyamg.py
  python/demo/demo_static-condensation.py
  python/demo/demo_stokes.py
  python/demo/demo_types.py
  python/dolfinx/fem/__init__.py
  python/dolfinx/fem/assemble.py
  python/dolfinx/fem/bcs.py
  python/dolfinx/fem/petsc.py
  python/dolfinx/wrappers/assemble.cpp
  python/dolfinx/wrappers/fem.cpp
  python/test/unit/fem/test_assemble_domains.py
  python/test/unit/fem/test_assemble_submesh.py
  python/test/unit/fem/test_bcs.py
  python/test/unit/fem/test_custom_basix_element.py
  python/test/unit/fem/test_fem_pipeline.py
  python/test/unit/fem/test_petsc_nonlinear_assembler.py
  python/test/unit/nls/test_newton.py
Labels: enhancement, documentation, housekeeping

#3445 Bump PETSC release
  docker/Dockerfile.test-env
Labels: docker, ci
