Repository FEniCS/dolfinx, pull requests merged in 2024-04, with the labels that each got.

#3107 Support DG-0 functions in VTXWriter
  cpp/dolfinx/io/ADIOS2Writers.h
  python/test/unit/io/test_adios2.py
Labels: enhancement

#3120 Move piece node outside of function loop in VTKFile
  cpp/dolfinx/io/VTKFile.cpp
Labels: bug, backport?

#3092 Let dlx.la.Vector manage the scope of the petsc4py wrapper (#1)
  python/demo/demo_elasticity.py
  python/demo/demo_static-condensation.py
  python/demo/demo_stokes.py
  python/demo/demo_waveguide/demo_half_loaded_waveguide.py
  python/dolfinx/fem/function.py
  python/dolfinx/la.py
  python/dolfinx/nls/petsc.py
  python/test/unit/fem/test_custom_assembler.py
  python/test/unit/fem/test_custom_basix_element.py
  python/test/unit/fem/test_dof_coordinates.py
  python/test/unit/fem/test_fem_pipeline.py
  python/test/unit/fem/test_nonlinear_assembler.py
  python/test/unit/fem/test_petsc_discrete_operators.py
  python/test/unit/la/test_krylov_solver.py
  python/test/unit/nls/test_newton.py
Labels: enhancement

#3127 Split linting and build steps in CI
  .github/workflows/ccpp.yml
Labels: ci

#3119 Template `distribute_entity_data` to support multiple data-types
  cpp/dolfinx/io/XDMFFile.cpp
  cpp/dolfinx/io/xdmf_utils.cpp
  cpp/dolfinx/io/xdmf_utils.h
  python/dolfinx/io/gmshio.py
  python/dolfinx/io/utils.py
  python/dolfinx/wrappers/io.cpp
Labels: enhancement

#3130 Bump dependency versions in Docker files
  docker/Dockerfile.end-user
  docker/Dockerfile.oneapi
  docker/Dockerfile.redhat
  docker/Dockerfile.test-env
Labels: housekeeping, docker, ci

#3131 macos version bumps for CI
  .github/workflows/conda.yml
  .github/workflows/macos.yml
Labels: ci

#3123 Make PETSc optional
  .github/workflows/ccpp.yml
  cpp/CMakeLists.txt
  cpp/cmake/modules/FindSCOTCH.cmake
  cpp/cmake/templates/DOLFINXConfig.cmake.in
  cpp/dolfinx/CMakeLists.txt
  cpp/dolfinx/common/defines.cpp
  cpp/dolfinx/common/defines.h
  cpp/dolfinx/fem/petsc.cpp
  cpp/dolfinx/fem/petsc.h
  cpp/dolfinx/la/dolfinx_la.h
  cpp/dolfinx/la/petsc.cpp
  cpp/dolfinx/la/petsc.h
  cpp/dolfinx/nls/NewtonSolver.cpp
  cpp/dolfinx/nls/NewtonSolver.h
  cpp/dolfinx/nls/dolfinx_nls.h
  cpp/test/common/sub_systems_manager.cpp
  python/dolfinx/wrappers/caster_petsc.h
  python/dolfinx/wrappers/dolfinx.cpp
  python/dolfinx/wrappers/petsc.cpp
Labels: enhancement

#3132 Remove legacy detection of PETSc scalar type
  cpp/CMakeLists.txt
  cpp/cmake/templates/DOLFINXConfig.cmake.in
  python/test/unit/fem/test_expression.py
  python/test/unit/fem/test_nonlinear_assembler.py
Labels: build, housekeeping

#3146 Re-activate commented lines in hyperelastic demo
  cpp/demo/hyperelasticity/hyperelasticity.py
  cpp/demo/hyperelasticity/main.cpp
Labels: demo, housekeeping

#3150 Updates for Conda weekly CI
  .github/workflows/conda.yml
Labels: ci

#3153 Run C++ unit tests on the no-PETSc CI job
  .github/workflows/ccpp.yml
Labels: ci

#3114 Interpolation to and from sub-meshes for co-dimension 0
  cpp/demo/hyperelasticity/main.cpp
  cpp/demo/interpolation_different_meshes/main.cpp
  cpp/dolfinx/fem/Function.h
  cpp/dolfinx/fem/interpolate.h
  python/dolfinx/fem/function.py
  python/dolfinx/wrappers/fem.cpp
  python/dolfinx/wrappers/mesh.cpp
  python/test/unit/fem/test_interpolation.py
Labels: enhancement, backport?

#3158 Interpolation into symmetric tensor
  cpp/dolfinx/fem/FiniteElement.cpp
  cpp/dolfinx/fem/FiniteElement.h
  cpp/dolfinx/fem/Function.h
  cpp/dolfinx/fem/FunctionSpace.h
  cpp/dolfinx/fem/interpolate.h
  python/test/unit/fem/test_symmetric_tensor.py
Labels: bug, backport?

#3151 Remove dynamic memory allocation inside tight loops in the Plaza refinement code
  cpp/dolfinx/refinement/plaza.cpp
  cpp/dolfinx/refinement/plaza.h
  cpp/dolfinx/refinement/utils.cpp
  cpp/dolfinx/refinement/utils.h
Labels: performance

#3170 Bump ADIOS2 version in Dockerfiles
  docker/Dockerfile.test-env
Labels: ci

#3175 TST: avoid unused variable in assert
  cpp/test/mesh/distributed_mesh.cpp
Labels: testing, backport?

#3176 Do CI linting in Actions image
  .github/workflows/ccpp.yml
Labels: ci

#3181 Do PETSc-free CI build in a clean image
  .github/workflows/ccpp.yml
Labels: ci

#3136 Reuse Basix element instead of recreating from generated code
  cpp/demo/biharmonic/main.cpp
  cpp/demo/hyperelasticity/main.cpp
  cpp/demo/poisson/main.cpp
  cpp/demo/poisson_matrix_free/main.cpp
  cpp/dolfinx/fem/FiniteElement.cpp
  cpp/dolfinx/fem/FiniteElement.h
  cpp/dolfinx/fem/utils.cpp
  cpp/dolfinx/fem/utils.h
  cpp/test/matrix.cpp
  python/demo/demo_axis/demo_axis.py
  python/demo/demo_cahn-hilliard.py
  python/demo/demo_lagrange_variants.py
  python/demo/demo_mixed-poisson.py
  python/demo/demo_pml/demo_pml.py
  python/demo/demo_scattering_boundary_conditions/demo_scattering_boundary_conditions.py
  python/demo/demo_stokes.py
  python/demo/demo_tnt-elements.py
  python/demo/demo_waveguide/demo_half_loaded_waveguide.py
  python/dolfinx/fem/dofmap.py
  python/dolfinx/fem/function.py
  python/dolfinx/fem/petsc.py
  python/dolfinx/jit.py
  python/dolfinx/wrappers/fem.cpp
  python/test/unit/fem/test_assembler.py
  python/test/unit/fem/test_bcs.py
  python/test/unit/fem/test_complex_assembler.py
  python/test/unit/fem/test_custom_basix_element.py
  python/test/unit/fem/test_dofmap.py
  python/test/unit/fem/test_element_integrals.py
  python/test/unit/fem/test_expression.py
  python/test/unit/fem/test_fem_pipeline.py
  python/test/unit/fem/test_function.py
  python/test/unit/fem/test_function_space.py
  python/test/unit/fem/test_interpolation.py
  python/test/unit/fem/test_mixed_element.py
  python/test/unit/fem/test_mixed_mesh_dofmap.py
  python/test/unit/fem/test_nonlinear_assembler.py
  python/test/unit/fem/test_petsc_discrete_operators.py
  python/test/unit/fem/test_symmetric_tensor.py
  python/test/unit/fem/test_symmetry.py
  python/test/unit/io/test_adios2.py
  python/test/unit/io/test_vtk.py
  python/test/unit/io/test_xdmf_function.py
  python/test/unit/la/test_vector_scatter.py
Labels: enhancement

#3184 Split PETSc and non-PETSc tests on CI
  .github/workflows/ccpp.yml
  .github/workflows/redhat.yml
  cpp/dolfinx/la/MatrixCSR.h
  cpp/dolfinx/la/Vector.h
  python/demo/demo_elasticity.py
  python/dolfinx/la.py
  python/dolfinx/wrappers/common.cpp
  python/dolfinx/wrappers/la.cpp
  python/pyproject.toml
  python/test/conftest.py
  python/test/unit/fem/test_assembler.py
  python/test/unit/fem/test_custom_assembler.py
  python/test/unit/fem/test_custom_basix_element.py
  python/test/unit/fem/test_dof_coordinates.py
  python/test/unit/fem/test_fem_pipeline.py
  python/test/unit/fem/test_interpolation.py
  python/test/unit/fem/test_nonlinear_assembler.py
  python/test/unit/fem/test_petsc_discrete_operators.py
  python/test/unit/fem/test_petsc_nonlinear_assembler.py
  python/test/unit/io/test_adios2.py
  python/test/unit/la/test_krylov_solver.py
  python/test/unit/la/test_nullspace.py
  python/test/unit/nls/test_newton.py
Labels: ci

#3185 Run Actions with OpenMPI and MPICH, and remove CircleCI config
  .circleci/config.yml
  .github/workflows/ccpp.yml
Labels: ci

#3189 Remove CircleCI badge from `README.md`
  README.md
Labels: housekeeping
