Repository FEniCS/dolfinx, pull requests merged in 2024-12, with the labels that each got.

#3552 Fix regression in FiniteElement Python wrapper
  python/dolfinx/fem/element.py
  python/test/unit/fem/test_dof_permuting.py
Labels: bug, high-priority

#3554 Further fixes to FiniteElement Python wrapper
  python/demo/demo_axis.py
  python/demo/demo_elasticity.py
  python/dolfinx/fem/element.py
  python/dolfinx/wrappers/fem.cpp
  python/test/unit/fem/test_discrete_operators.py
  python/test/unit/fem/test_dof_permuting.py
  python/test/unit/fem/test_dofmap.py
  python/test/unit/fem/test_expression.py
  python/test/unit/fem/test_function_space.py
  python/test/unit/fem/test_interpolation.py
  python/test/unit/fem/test_petsc_discrete_operators.py
Labels: bug, nanobind

#3573 Single code path for mesh creation
  cpp/dolfinx/common/sort.h
  cpp/dolfinx/fem/assemble_matrix_impl.h
  cpp/dolfinx/fem/assemble_vector_impl.h
  cpp/dolfinx/geometry/BoundingBoxTree.h
  cpp/dolfinx/graph/partitioners.cpp
  cpp/dolfinx/mesh/Mesh.h
  cpp/dolfinx/mesh/Topology.cpp
  cpp/dolfinx/mesh/graphbuild.cpp
  cpp/dolfinx/mesh/graphbuild.h
  cpp/dolfinx/mesh/utils.cpp
  cpp/dolfinx/mesh/utils.h
  cpp/test/mesh/refinement/rectangle.cpp
  python/dolfinx/mesh.py
  python/dolfinx/wrappers/fem.cpp
  python/test/unit/fem/test_assembler.py
Labels: enhancement, housekeeping

#3574 Fix doc typos
  cpp/dolfinx/mesh/Topology.h
  cpp/dolfinx/mesh/utils.h
Labels: documentation, housekeeping

#3575 Mesh `Geometry` improvements for mixed topology
  cpp/dolfinx/mesh/Geometry.h
  cpp/dolfinx/mesh/utils.h
  python/dolfinx/wrappers/mesh.cpp
Labels: enhancement

#3563 Modify demo_helmholtz.py to solve for plane wave solution in complex mode
  python/demo/demo_helmholtz.py
Labels: demo

#3577 Topology doc and code path improvements
  cpp/dolfinx/fem/dofmapbuilder.cpp
  cpp/dolfinx/mesh/Geometry.h
  cpp/dolfinx/mesh/Topology.cpp
  cpp/dolfinx/mesh/Topology.h
  cpp/dolfinx/mesh/permutationcomputation.cpp
  cpp/dolfinx/mesh/topologycomputation.cpp
  cpp/dolfinx/mesh/topologycomputation.h
  python/dolfinx/wrappers/mesh.cpp
Labels: documentation, housekeeping

#3578 Move Discourse and Slack to top of README
  README.md
Labels: housekeeping

#3579 Simplify and improve Topology interface
  cpp/dolfinx/mesh/Topology.cpp
  cpp/dolfinx/mesh/Topology.h
  cpp/dolfinx/mesh/topologycomputation.cpp
  cpp/dolfinx/mesh/topologycomputation.h
  python/dolfinx/mesh.py
  python/dolfinx/wrappers/mesh.cpp
  python/test/unit/mesh/test_mixed_topology.py
Labels: enhancement, housekeeping

#3576 VTKHDF mesh I/O
  cpp/dolfinx/io/CMakeLists.txt
  cpp/dolfinx/io/HDF5Interface.h
  cpp/dolfinx/io/VTKHDF.h
  cpp/dolfinx/io/cells.cpp
  cpp/dolfinx/io/dolfinx_io.h
  python/dolfinx/io/__init__.py
  python/dolfinx/io/vtkhdf.py
  python/dolfinx/wrappers/io.cpp
  python/test/unit/__init__.py
  python/test/unit/conftest.py
  python/test/unit/io/test_vtkhdf.py
Labels: enhancement, io
