Repository FEniCS/dolfinx, pull requests merged in 2024-03, with the labels that each got.

#3068 C++ demo documentation refinements
  cpp/demo/biharmonic/biharmonic.py
  cpp/demo/biharmonic/main.cpp
  cpp/demo/custom_kernel/main.cpp
  cpp/demo/hyperelasticity/hyperelasticity.py
  cpp/demo/hyperelasticity/main.cpp
  cpp/demo/interpolation-io/main.cpp
  cpp/demo/interpolation_different_meshes/main.cpp
  cpp/demo/mixed_topology/main.cpp
  cpp/demo/poisson/main.cpp
  cpp/demo/poisson/poisson.py
  cpp/demo/poisson_matrix_free/main.cpp
  cpp/demo/poisson_matrix_free/poisson.py
  cpp/doc/Doxyfile
  cpp/doc/source/api.rst
  cpp/doc/source/demo.rst
  cpp/doc/source/index.rst
Labels: documentation

#3066 Mark IndexMaps on communicators with size 1 as non-overlapped
  cpp/dolfinx/common/IndexMap.cpp
Labels: enhancement

#3082 Bump versions in Dockerfiles
  docker/Dockerfile.end-user
  docker/Dockerfile.oneapi
  docker/Dockerfile.redhat
  docker/Dockerfile.test-env
Labels: docker, ci

#3079 Add mixed-domain matrix assembly for facet integrals (codimension 0)
  cpp/dolfinx/fem/Form.h
  cpp/dolfinx/fem/assemble_matrix_impl.h
  cpp/dolfinx/fem/sparsitybuild.cpp
  cpp/dolfinx/fem/sparsitybuild.h
  cpp/dolfinx/fem/utils.h
  python/test/unit/fem/test_assemble_submesh.py
Labels: enhancement

#3085 Simplify `IndexMap` overlap
  cpp/demo/poisson_matrix_free/main.cpp
  cpp/dolfinx/common/IndexMap.cpp
  cpp/dolfinx/common/IndexMap.h
  cpp/dolfinx/common/Scatterer.h
  cpp/dolfinx/graph/ordering.cpp
  cpp/dolfinx/io/VTKFile.cpp
  cpp/dolfinx/io/cells.cpp
  cpp/dolfinx/io/xdmf_utils.cpp
  cpp/dolfinx/la/Vector.h
  cpp/dolfinx/mesh/Topology.cpp
  cpp/dolfinx/mesh/topologycomputation.cpp
  cpp/dolfinx/mesh/utils.h
  cpp/test/common/index_map.cpp
  cpp/test/matrix.cpp
  python/doc/source/styleguide_cpp.rst
  python/dolfinx/utils.py
  python/test/unit/common/test_mpi.py
  python/test/unit/fem/test_custom_basix_element.py
  python/test/unit/fem/test_fem_pipeline.py
  python/test/unit/fem/test_vector_assemble.py
  python/test/unit/la/test_matrix_csr.py
  python/test/unit/la/test_matrix_vector.py
  python/test/unit/la/test_vector_scatter.py
  python/test/unit/mesh/test_higher_order_mesh.py
Labels: enhancement

#3071 Add multiple dofmaps and elements to Geometry
  cpp/dolfinx/fem/dofmapbuilder.cpp
  cpp/dolfinx/fem/utils.cpp
  cpp/dolfinx/fem/utils.h
  cpp/dolfinx/mesh/Geometry.h
  python/dolfinx/wrappers/fem.cpp
  python/dolfinx/wrappers/mesh.cpp
  python/test/unit/fem/test_mixed_mesh_dofmap.py
  python/test/unit/mesh/test_mixed_topology.py
Labels: enhancement

#3086 Updates for `mdspan`
  cpp/dolfinx/fem/DofMap.cpp
  cpp/dolfinx/fem/Expression.h
  cpp/dolfinx/fem/Function.h
  cpp/dolfinx/fem/FunctionSpace.h
  cpp/dolfinx/fem/assemble_matrix_impl.h
  cpp/dolfinx/fem/assemble_scalar_impl.h
  cpp/dolfinx/fem/assemble_vector_impl.h
  cpp/dolfinx/fem/discreteoperators.h
  cpp/dolfinx/fem/interpolate.h
  cpp/dolfinx/geometry/utils.h
  cpp/dolfinx/io/ADIOS2Writers.h
  cpp/dolfinx/io/vtk_utils.h
  cpp/dolfinx/io/xdmf_function.cpp
  cpp/dolfinx/io/xdmf_mesh.cpp
  cpp/dolfinx/mesh/Geometry.h
  cpp/dolfinx/mesh/utils.h
  cpp/dolfinx/refinement/plaza.h
  cpp/dolfinx/refinement/utils.h
  python/dolfinx/wrappers/fem.cpp
Labels: housekeeping

#3091 Add option to preserve sub-IndexMap ghost ordering
  cpp/dolfinx/common/IndexMap.cpp
  cpp/dolfinx/common/IndexMap.h
  cpp/dolfinx/fem/DofMap.cpp
  cpp/dolfinx/mesh/Geometry.h
  cpp/dolfinx/mesh/Topology.cpp
  python/dolfinx/wrappers/common.cpp
  python/test/unit/fem/test_function_space.py
Labels: bug, enhancement

#3099 Fix sub index map destination rank computation
  cpp/dolfinx/common/IndexMap.cpp
  python/test/unit/common/test_index_map.py
Labels: bug

#3104 Small change to `MPI_I(s)send` buffer allocation
  cpp/dolfinx/common/MPI.cpp
Labels: housekeeping

#3088 Revert change to Python interface of non-matching interpolation data
  python/dolfinx/fem/__init__.py
  python/test/unit/fem/test_interpolation.py
Labels: bug
