Repository FEniCS/dolfinx, pull requests merged in 2024-06, with the labels that each got.

#3244 Enable SCOTCH detection via CMake `CONFIG` mode.
  cpp/CMakeLists.txt
  cpp/cmake/modules/FindSCOTCH.cmake
  cpp/dolfinx/CMakeLists.txt
Labels: build

#3253 Allow dx and dx(i) in same form
  python/dolfinx/fem/forms.py
  python/test/unit/fem/test_assemble_domains.py
Labels: bug

#3254 Small Basix type updates
  python/test/unit/fem/test_expression.py
  python/test/unit/mesh/test_cell.py
  python/test/unit/mesh/test_mesh.py
Labels: housekeeping

#3246 Make compile time options compile time constants
  cpp/dolfinx/common/defines.cpp
  cpp/dolfinx/common/defines.h
Labels: enhancement

#3224 Add support for mixed-domain problems of codimension 1
  cpp/dolfinx/fem/Form.h
  cpp/dolfinx/fem/assemble_matrix_impl.h
  cpp/dolfinx/fem/assemble_scalar_impl.h
  cpp/dolfinx/fem/assemble_vector_impl.h
  cpp/dolfinx/fem/utils.h
  python/demo/demo_hdg.py
  python/doc/source/demos.rst
  python/dolfinx/fem/forms.py
  python/test/unit/fem/test_assemble_submesh.py
Labels: enhancement

#3261 Prepare for release of numpy 2.0 by using ruff ruleset
  python/pyproject.toml
Labels: dependencies

#3264 Add indices of missing connectivity in error message
  cpp/CMakeLists.txt
  cpp/dolfinx/mesh/utils.h
Labels: enhancement

#3260 Use `enabled_coefficients` to restrict packing of coefficients
  cpp/demo/custom_kernel/main.cpp
  cpp/dolfinx/fem/Form.h
  cpp/dolfinx/fem/utils.h
  python/demo/demo_static-condensation.py
  python/dolfinx/wrappers/fem.cpp
  python/test/unit/fem/test_custom_jit_kernels.py
Labels: bug, performance, high-priority

#3266 Remove `.mailmap`
  .mailmap
Labels: housekeeping

#3270 Pin nanobind version in Spack CI test
  .github/workflows/spack.yml
Labels: ci

#3277 MacOS CI fixes
  .github/workflows/macos.yml
Labels: housekeeping, ci

#3276 Fix pyvista actions
  .github/workflows/pyvista.yml
  cpp/dolfinx/mesh/utils.h
  python/demo/demo_types.py
Labels: bug, housekeeping, ci

#3263 Data independent form compilation for Python interface
  python/dolfinx/fem/__init__.py
  python/dolfinx/fem/forms.py
  python/dolfinx/wrappers/fem.cpp
  python/test/unit/fem/test_assemble_mesh_independent_form.py
Labels: enhancement
