Repository FEniCS/dolfinx, pull requests merged in 2024-02, with the labels that each got.

#3029 Fix some use of deprecated Python and NumPy functionality in tests
  python/test/unit/common/test_version.py
  python/test/unit/fem/test_expression.py
Labels: housekeeping

#3030 Fix pytest marker warning and some doc typos
  python/dolfinx/la.py
  python/pyproject.toml
  python/test/conftest.py
Labels: housekeeping, ci

#3031 Fix leak for `MPI_Datatype`
  cpp/dolfinx/io/xdmf_utils.cpp
Labels: bug

#3033 Updates for ruff
  python/doc/source/conf.py
  python/dolfinx/mesh.py
  python/pyproject.toml
Labels: housekeeping, ci

#3032 Bump dependency versions
  docker/Dockerfile.end-user
  docker/Dockerfile.oneapi
  docker/Dockerfile.redhat
  docker/Dockerfile.test-env
Labels: docker

#3034 Re-enable a test
  python/test/unit/fem/test_dofmap.py
Labels: ci

#3036 Add some PETSc `destroy` to avoid MPICH leak messages
  python/test/unit/fem/test_assembler.py
  python/test/unit/fem/test_nonlinear_assembler.py
  python/test/unit/la/test_nullspace.py
Labels: housekeeping, ci

#3048 Bump openmpi patch version
  docker/Dockerfile.test-env
Labels: docker

#3043 Better error messages if mesh dtype is not compatible with function space dtype
  python/demo/demo_static-condensation.py
  python/dolfinx/fem/bcs.py
  python/dolfinx/fem/element.py
  python/dolfinx/fem/forms.py
  python/dolfinx/fem/function.py
  python/dolfinx/geometry.py
  python/dolfinx/io/utils.py
  python/dolfinx/la.py
  python/dolfinx/mesh.py
  python/dolfinx/wrappers/fem.cpp
  python/dolfinx/wrappers/la.cpp
  python/dolfinx/wrappers/mesh.cpp
  python/dolfinx/wrappers/numpy_dtype.h
Labels: housekeeping

#3057 Check that UFCx kernel functions are not `null`
  cpp/dolfinx/fem/utils.h
  cpp/test/io.cpp
  python/dolfinx/wrappers/io.cpp
Labels: enhancement

#3058 Remove `.flake8` file
  .flake8
Labels: housekeeping

#3073 Add pair header for SparsityPattern graph return type
  python/dolfinx/wrappers/la.cpp
Labels: bug

#3074 Documentation fix
  cpp/dolfinx/mesh/utils.h
Labels: documentation

#3075 Add numpy interface to `dolfinx.cpp.mesh.extract_topology`
  python/dolfinx/wrappers/mesh.cpp
Labels: enhancement

#3056 Add maps for mixed-domain assembly
  cpp/demo/custom_kernel/main.cpp
  cpp/dolfinx/fem/ElementDofLayout.h
  cpp/dolfinx/fem/FiniteElement.h
  cpp/dolfinx/fem/Form.h
  cpp/dolfinx/fem/assemble_matrix_impl.h
  cpp/dolfinx/fem/assemble_vector_impl.h
  cpp/dolfinx/fem/assembler.h
  cpp/dolfinx/fem/sparsitybuild.cpp
  cpp/dolfinx/fem/sparsitybuild.h
  cpp/dolfinx/fem/traits.h
  cpp/dolfinx/fem/utils.h
  cpp/dolfinx/mesh/utils.h
  python/demo/demo_static-condensation.py
  python/dolfinx/fem/forms.py
  python/dolfinx/wrappers/assemble.cpp
  python/dolfinx/wrappers/fem.cpp
  python/dolfinx/wrappers/petsc.cpp
  python/test/unit/fem/test_assemble_submesh.py
  python/test/unit/fem/test_custom_jit_kernels.py
Labels: enhancement
