Repository FEniCS/dolfinx, pull requests merged in 2024-05, with the labels that each got.

#3192 Update Docker base images to `ubuntu:24.04`
  docker/Dockerfile.oneapi
  docker/Dockerfile.test-env
Labels: docker

#3193 Fix patch level for HDF in Dockerfile
  cpp/dolfinx/common/loguru.cpp
  docker/Dockerfile.test-env
  python/test/unit/common/test_timer.py
Labels: docker, ci

#3194 Spack ci update
  .github/workflows/ccpp.yml
  .github/workflows/sonarcloud.yml
  .github/workflows/spack.yml
  cpp/dolfinx/common/loguru.cpp
  python/demo/demo_axis/demo_axis.py
  python/demo/demo_helmholtz.py
  python/demo/demo_mixed-poisson.py
  python/demo/demo_pml/demo_pml.py
  python/demo/demo_scattering_boundary_conditions/demo_scattering_boundary_conditions.py
  python/demo/demo_stokes.py
  python/demo/demo_waveguide/demo_half_loaded_waveguide.py
Labels: ci

#3197 Add petsc4py build requirements
  docker/Dockerfile.test-env
Labels: docker

#3203 Spack Actions CI update
  .github/workflows/redhat.yml
  .github/workflows/spack.yml
Labels: ci

#3205 Simplify oneAPI and Rocky images
  .github/workflows/oneapi.yml
  .github/workflows/redhat.yml
  docker/Dockerfile.oneapi
  docker/Dockerfile.redhat
Labels: docker

#3206 Exit demos that require PETSc when PETSc is not available
  .github/workflows/ccpp.yml
  cpp/dolfinx/geometry/BoundingBoxTree.h
  python/demo/demo_axis.py
  python/demo/demo_axis/mesh_sphere_axis.py
  python/demo/demo_biharmonic.py
  python/demo/demo_cahn-hilliard.py
  python/demo/demo_elasticity.py
  python/demo/demo_gmsh.py
  python/demo/demo_half_loaded_waveguide.py
  python/demo/demo_helmholtz.py
  python/demo/demo_mixed-poisson.py
  python/demo/demo_navier-stokes.py
  python/demo/demo_pml.py
  python/demo/demo_pml/efficiencies_pml_demo.py
  python/demo/demo_pml/mesh_wire_pml.py
  python/demo/demo_poisson.py
  python/demo/demo_scattering_boundary_conditions.py
  python/demo/demo_scattering_boundary_conditions/analytical_efficiencies_wire.py
  python/demo/demo_scattering_boundary_conditions/mesh_wire.py
  python/demo/demo_static-condensation.py
  python/demo/demo_stokes.py
  python/demo/demo_tnt-elements.py
  python/demo/demo_waveguide/analytical_modes.py
  python/dolfinx/__init__.py
  python/dolfinx/common.py
Labels: demo, ci

#3177 Make standalone function for interpolation over non-matching meshes
  cpp/demo/hyperelasticity/main.cpp
  cpp/demo/interpolation_different_meshes/main.cpp
  cpp/dolfinx/fem/Expression.h
  cpp/dolfinx/fem/Function.h
  cpp/dolfinx/fem/interpolate.h
  cpp/dolfinx/geometry/utils.h
  python/dolfinx/fem/__init__.py
  python/dolfinx/fem/assemble.py
  python/dolfinx/fem/bcs.py
  python/dolfinx/fem/dofmap.py
  python/dolfinx/fem/forms.py
  python/dolfinx/fem/function.py
  python/dolfinx/fem/petsc.py
  python/dolfinx/geometry.py
  python/dolfinx/wrappers/fem.cpp
  python/dolfinx/wrappers/geometry.cpp
  python/test/unit/fem/test_interpolation.py
Labels: bug, high-priority

#3217 Add `spdlog` to doc install requirements
  python/doc/source/installation.rst
Labels: documentation

#3218 Remove spdlog install from CI yaml
  .github/workflows/ccpp.yml
  .github/workflows/oneapi.yml
  .github/workflows/redhat.yml
Labels: ci

#3209 Orient mesh entities consistently and generalise `entities_to_geometry`
  cpp/dolfinx/fem/CoordinateElement.cpp
  cpp/dolfinx/fem/CoordinateElement.h
  cpp/dolfinx/geometry/BoundingBoxTree.h
  cpp/dolfinx/mesh/Geometry.h
  cpp/dolfinx/mesh/topologycomputation.cpp
  cpp/dolfinx/mesh/topologycomputation.h
  cpp/dolfinx/mesh/utils.h
  python/demo/demo_axis.py
  python/demo/demo_pml.py
  python/dolfinx/mesh.py
  python/dolfinx/plot.py
  python/dolfinx/wrappers/mesh.cpp
  python/test/unit/mesh/test_face.py
  python/test/unit/mesh/test_ghost_mesh.py
  python/test/unit/mesh/test_mesh.py
  python/test/unit/mesh/test_mesh_partitioners.py
Labels: enhancement

#3220 Install unzip package in CI for Spack
  .github/workflows/spack.yml
Labels: ci

#3221 Improvements and fixes for C++ Doxygen/breathe/sphinx doc processing
  cpp/doc/source/fem.rst
  cpp/dolfinx/fem/DirichletBC.h
  cpp/dolfinx/fem/DofMap.cpp
  cpp/dolfinx/fem/DofMap.h
  cpp/dolfinx/fem/Form.h
Labels: documentation, housekeeping

#3222 Improve documentation for `pyamg` demo
  python/demo/demo_pyamg.py
Labels: documentation

#3112 Add docstrings to submesh creation in Python interface
  python/dolfinx/mesh.py
Labels: documentation

#3105 Replace `nb::any` with -1 and add argument to `nb::ndarray` in preparation of next nanobind release
  .github/workflows/ccpp.yml
  .github/workflows/conda.yml
  .github/workflows/oneapi.yml
  .github/workflows/redhat.yml
  cpp/cmake/templates/DOLFINXConfig.cmake.in
  docker/Dockerfile.test-env
  python/build-requirements.txt
  python/dolfinx/wrappers/assemble.cpp
  python/dolfinx/wrappers/common.cpp
  python/dolfinx/wrappers/fem.cpp
  python/dolfinx/wrappers/geometry.cpp
  python/dolfinx/wrappers/graph.cpp
  python/dolfinx/wrappers/la.cpp
  python/dolfinx/wrappers/log.cpp
  python/dolfinx/wrappers/mesh.cpp
  python/pyproject.toml
Labels: backport?, nanobind

#3232 Docker simplify (phase 2)
  .github/workflows/ccpp.yml
  docker/Dockerfile.test-env
  python/build-requirements.txt
  python/pyproject.toml
Labels: ci

#3235 Dockerfile end-user updates
  .github/workflows/docker-end-user.yml
  cpp/dolfinx/common/CMakeLists.txt
  docker/Dockerfile.end-user
Labels: docker

#3227 Generalize all output formats for general length vectors and tensors
  cpp/dolfinx/io/ADIOS2Writers.h
  cpp/dolfinx/io/VTKFile.cpp
  cpp/dolfinx/io/xdmf_function.cpp
Labels: bug, io, backport?

#3239 Bump dependency versions in Dockerfile
  docker/Dockerfile.oneapi
  docker/Dockerfile.redhat
  docker/Dockerfile.test-env
Labels: housekeeping, docker
