Repository FEniCS/dolfinx, pull requests merged in 2024-10, with the labels that each got.

#3447 Return source rank for each node in constant degree adjacency list when distributing
  cpp/dolfinx/graph/partition.cpp
  cpp/dolfinx/graph/partition.h
  cpp/dolfinx/mesh/utils.h
Labels: enhancement

#3448 Use earlier NumPy version in Dockerfile
  docker/Dockerfile.test-env
Labels: docker

#3444 Pass graph partitioner to `mesh::refine`
  cpp/dolfinx/mesh/MeshTags.h
  cpp/dolfinx/refinement/refine.h
  cpp/dolfinx/refinement/utils.h
  cpp/test/mesh/refinement/interval.cpp
  cpp/test/mesh/refinement/rectangle.cpp
  python/dolfinx/mesh.py
  python/dolfinx/wrappers/mesh.cpp
  python/dolfinx/wrappers/mesh.h
  python/dolfinx/wrappers/refinement.cpp
  python/test/unit/refinement/test_interval.py
  python/test/unit/refinement/test_refinement.py
Labels: enhancement

#3449 Add comment in `pyproject.toml` on cffi version pin
  python/pyproject.toml
Labels: housekeeping

#3451 Move to py311 for oneAPI test
  python/conda-oneapi-test-env.yml
Labels: ci

#3450 Simplify blocked demos using `extract_blocks`
  python/demo/demo_hdg.py
  python/demo/demo_navier-stokes.py
Labels: demo

#3453 Fix bug in distribute
  cpp/dolfinx/graph/partition.cpp
Labels: bug, high-priority

#3455 Vertex submesh support
  cpp/dolfinx/mesh/utils.h
  python/dolfinx/mesh.py
  python/test/unit/mesh/test_mesh.py
Labels: enhancement

#3452 Fix codim-1 assembly on interior facets
  cpp/dolfinx/fem/Form.h
  python/test/unit/fem/test_assemble_submesh.py
Labels: bug, high-priority

#3472 Spack CI update
  .github/workflows/spack.yml
Labels: packaging, ci

#3473 Update version in Spack CI file
  .github/workflows/spack.yml
Labels: ci

#3479 Use standard C++20 (no GNU extensions)
  cpp/cmake/scripts/generate-cmakefiles.py
  cpp/demo/biharmonic/CMakeLists.txt
  cpp/demo/codim_0_assembly/CMakeLists.txt
  cpp/demo/custom_kernel/CMakeLists.txt
  cpp/demo/hyperelasticity/CMakeLists.txt
  cpp/demo/interpolation-io/CMakeLists.txt
  cpp/demo/interpolation_different_meshes/CMakeLists.txt
  cpp/demo/poisson/CMakeLists.txt
  cpp/demo/poisson_matrix_free/CMakeLists.txt
  cpp/dolfinx/CMakeLists.txt
  python/CMakeLists.txt
Labels: build

#3486 Bump adios2, HDF5, MPICH and OPENMPI in docker images.
  docker/Dockerfile.redhat
  docker/Dockerfile.test-env
Labels: docker

#3484 Revised `Timer`, now using `std::chrono`
  .github/workflows/ccpp.yml
  cpp/CMakeLists.txt
  cpp/cmake/templates/DOLFINXConfig.cmake.in
  cpp/demo/custom_kernel/main.cpp
  cpp/dolfinx/CMakeLists.txt
  cpp/dolfinx/common/CMakeLists.txt
  cpp/dolfinx/common/TimeLogManager.h
  cpp/dolfinx/common/TimeLogger.cpp
  cpp/dolfinx/common/TimeLogger.h
  cpp/dolfinx/common/Timer.cpp
  cpp/dolfinx/common/Timer.h
  cpp/dolfinx/common/timing.cpp
  cpp/dolfinx/common/timing.h
  cpp/vcpkg.json
  docker/Dockerfile.redhat
  docker/Dockerfile.test-env
  python/dolfinx/common.py
  python/dolfinx/wrappers/common.cpp
  python/test/unit/common/test_timer.py
  python/test/unit/fem/test_custom_jit_kernels.py
Labels: task, dependencies

#3490 Improve Newton solver docs
  cpp/dolfinx/nls/NewtonSolver.h
Labels: documentation

#3488 Fixes to `Timer` logic
  cpp/dolfinx/common/Timer.h
  python/dolfinx/common.py
  python/dolfinx/wrappers/common.cpp
  python/test/unit/common/test_timer.py
Labels: enhancement

#3487 Allow access to logged timer data
  cpp/dolfinx/common/TimeLogger.cpp
  cpp/dolfinx/common/TimeLogger.h
  cpp/dolfinx/common/Timer.h
  cpp/dolfinx/common/timing.cpp
  cpp/dolfinx/common/timing.h
  python/dolfinx/common.py
  python/dolfinx/wrappers/common.cpp
  python/test/unit/common/test_timer.py
Labels: enhancement
