Repository FEniCS/dolfinx, pull requests merged in 2024-01, with the labels that each got.

#2947 Work-arounds for latest doxygen release
  cpp/dolfinx/fem/FiniteElement.cpp
  cpp/dolfinx/fem/FiniteElement.h
  cpp/dolfinx/fem/assemble_vector_impl.h
Labels: housekeeping

#2890 Fix `create_submesh` by generalising sub index map creation
  cpp/dolfinx/common/IndexMap.cpp
  cpp/dolfinx/common/IndexMap.h
  cpp/dolfinx/common/MPI.cpp
  cpp/dolfinx/common/Scatterer.h
  cpp/dolfinx/fem/DirichletBC.cpp
  cpp/dolfinx/fem/DofMap.cpp
  cpp/dolfinx/fem/dofmapbuilder.cpp
  cpp/dolfinx/io/VTKFile.cpp
  cpp/dolfinx/io/vtk_utils.h
  cpp/dolfinx/io/xdmf_mesh.cpp
  cpp/dolfinx/la/MatrixCSR.h
  cpp/dolfinx/la/SparsityPattern.cpp
  cpp/dolfinx/mesh/Geometry.h
  cpp/dolfinx/mesh/Topology.cpp
  cpp/dolfinx/refinement/utils.cpp
  python/dolfinx/wrappers/common.cpp
  python/test/unit/common/test_index_map.py
  python/test/unit/fem/test_assemble_submesh.py
  python/test/unit/la/test_matrix_csr.py
Labels: enhancement

#2960 Support creation of meshes from Basix elements from Python
  python/demo/demo_lagrange_variants.py
  python/demo/demo_navier-stokes.py
  python/demo/demo_static-condensation.py
  python/dolfinx/common.py
  python/dolfinx/fem/__init__.py
  python/dolfinx/fem/bcs.py
  python/dolfinx/fem/dofmap.py
  python/dolfinx/fem/element.py
  python/dolfinx/fem/forms.py
  python/dolfinx/fem/function.py
  python/dolfinx/fem/petsc.py
  python/dolfinx/geometry.py
  python/dolfinx/io/gmshio.py
  python/dolfinx/io/utils.py
  python/dolfinx/la.py
  python/dolfinx/mesh.py
  python/dolfinx/wrappers/fem.cpp
  python/pyproject.toml
  python/test/unit/fem/test_assembler.py
  python/test/unit/fem/test_dof_permuting.py
  python/test/unit/fem/test_element_integrals.py
  python/test/unit/fem/test_function.py
  python/test/unit/fem/test_function_space.py
  python/test/unit/fem/test_interpolation.py
  python/test/unit/fem/test_petsc_discrete_operators.py
  python/test/unit/fem/test_vector_function.py
  python/test/unit/geometry/test_gjk.py
  python/test/unit/io/test_adios2.py
  python/test/unit/io/test_vtk.py
  python/test/unit/io/test_xdmf_mesh.py
  python/test/unit/mesh/test_cell.py
  python/test/unit/mesh/test_higher_order_mesh.py
  python/test/unit/mesh/test_manifold_point_search.py
  python/test/unit/mesh/test_mesh.py
  python/test/unit/mesh/test_mesh_partitioners.py
Labels: enhancement

#2963 Fix `IndexMap->global_to_local()`
  cpp/dolfinx/common/IndexMap.cpp
Labels: bug

#2955 Allow for blocked elements with block size 1
  cpp/dolfinx/fem/FiniteElement.cpp
  cpp/dolfinx/fem/FiniteElement.h
Labels: bug

#2954 Simplify mesh creation interface and algorithms
  cpp/demo/hyperelasticity/main.cpp
  cpp/demo/interpolation_different_meshes/main.cpp
  cpp/demo/mixed_topology/CMakeLists.txt
  cpp/dolfinx/fem/DirichletBC.cpp
  cpp/dolfinx/fem/DofMap.cpp
  cpp/dolfinx/fem/Expression.h
  cpp/dolfinx/fem/Function.h
  cpp/dolfinx/fem/FunctionSpace.h
  cpp/dolfinx/fem/assemble_matrix_impl.h
  cpp/dolfinx/fem/assemble_scalar_impl.h
  cpp/dolfinx/fem/assemble_vector_impl.h
  cpp/dolfinx/fem/discreteoperators.h
  cpp/dolfinx/fem/dofmapbuilder.cpp
  cpp/dolfinx/fem/dofmapbuilder.h
  cpp/dolfinx/fem/interpolate.h
  cpp/dolfinx/fem/utils.cpp
  cpp/dolfinx/fem/utils.h
  cpp/dolfinx/geometry/utils.h
  cpp/dolfinx/io/ADIOS2Writers.h
  cpp/dolfinx/io/VTKFile.cpp
  cpp/dolfinx/io/XDMFFile.cpp
  cpp/dolfinx/io/vtk_utils.h
  cpp/dolfinx/io/xdmf_function.cpp
  cpp/dolfinx/io/xdmf_mesh.cpp
  cpp/dolfinx/io/xdmf_utils.cpp
  cpp/dolfinx/io/xdmf_utils.h
  cpp/dolfinx/mesh/Geometry.h
  cpp/dolfinx/mesh/MeshTags.h
  cpp/dolfinx/mesh/Topology.cpp
  cpp/dolfinx/mesh/Topology.h
  cpp/dolfinx/mesh/generation.h
  cpp/dolfinx/mesh/permutationcomputation.cpp
  cpp/dolfinx/mesh/topologycomputation.cpp
  cpp/dolfinx/mesh/utils.cpp
  cpp/dolfinx/mesh/utils.h
  cpp/dolfinx/refinement/plaza.h
  cpp/dolfinx/refinement/refine.h
  cpp/dolfinx/refinement/utils.h
  cpp/test/mesh/distributed_mesh.cpp
  python/dolfinx/io/gmshio.py
  python/dolfinx/io/utils.py
  python/dolfinx/mesh.py
  python/dolfinx/plot.py
  python/dolfinx/wrappers/fem.cpp
  python/dolfinx/wrappers/io.cpp
  python/dolfinx/wrappers/mesh.cpp
  python/test/unit/fem/test_assembler.py
  python/test/unit/fem/test_dof_permuting.py
  python/test/unit/fem/test_dofmap.py
  python/test/unit/fem/test_expression.py
  python/test/unit/fem/test_interpolation.py
  python/test/unit/io/test_adios2.py
  python/test/unit/io/test_xdmf_function.py
  python/test/unit/io/test_xdmf_meshdata.py
  python/test/unit/mesh/test_mesh.py
Labels: enhancement, performance

#2964 Update stokes demo tolerance
  python/demo/demo_stokes.py
Labels: testing

#2952 Add dofmap consistency check for `VTXWriter` and `FidesWriter`
  cpp/dolfinx/fem/DofMap.h
  cpp/dolfinx/io/ADIOS2Writers.h
Labels: enhancement

#2967 Type hint fixes
  python/dolfinx/fem/forms.py
  python/dolfinx/fem/function.py
  python/dolfinx/io/utils.py
Labels: type-hints

#2968 Improve FFI support for calling C functions from Python/Numba
  python/demo/demo_static-condensation.py
  python/dolfinx/__init__.py
  python/dolfinx/fem/__init__.py
  python/dolfinx/fem/petsc.py
  python/dolfinx/mesh.py
  python/dolfinx/utils.py
  python/pyproject.toml
  python/test/unit/common/test_index_map.py
  python/test/unit/fem/test_custom_assembler.py
  python/test/unit/fem/test_custom_jit_kernels.py
  python/test/unit/mesh/test_mesh.py
Labels: enhancement, housekeeping

#2982 Implement VTK I/O for arbitrary degree hex cells
  cpp/dolfinx/io/cells.cpp
  cpp/dolfinx/io/cells.h
  cpp/dolfinx/io/vtk_utils.h
Labels: io

#2992 Improvements to `demo_helmholtz.py` and `demo_scattering_boundary_conditions.py`
  python/demo/demo_helmholtz.py
  python/demo/demo_scattering_boundary_conditions/demo_scattering_boundary_conditions.py
Labels: documentation

#2985 Implement VTK I/O for arbitrary degree tetrahedron cells
  cpp/dolfinx/io/cells.cpp
  python/test/unit/mesh/test_higher_order_mesh.py
Labels: io, backport?

#2977 Simplify access to wrapped C++ form classes
  python/demo/demo_static-condensation.py
  python/dolfinx/__init__.py
  python/dolfinx/fem/__init__.py
  python/dolfinx/fem/forms.py
  python/dolfinx/utils.py
  python/test/unit/fem/test_custom_jit_kernels.py
Labels: proposal

#2993 Stop cffi_utils failing on KeyError
  python/dolfinx/utils.py
  python/test/unit/fem/test_custom_assembler.py
Labels: bug

#3005 Update all notebooks to render correctly on web page and in notebooks.
  python/demo/demo_axis/demo_axis.py
  python/demo/demo_biharmonic.py
  python/demo/demo_cahn-hilliard.py
  python/demo/demo_mixed-poisson.py
  python/demo/demo_navier-stokes.py
  python/demo/demo_pml/demo_pml.py
  python/demo/demo_poisson.py
  python/demo/demo_scattering_boundary_conditions/demo_scattering_boundary_conditions.py
  python/demo/demo_stokes.py
  python/demo/demo_tnt-elements.py
  python/demo/demo_waveguide/demo_half_loaded_waveguide.py
Labels: documentation, backport?

#2994 Topology computation for mixed topology
  cpp/dolfinx/mesh/Topology.cpp
  cpp/dolfinx/mesh/Topology.h
  cpp/dolfinx/mesh/topologycomputation.cpp
  cpp/dolfinx/mesh/topologycomputation.h
  python/dolfinx/wrappers/mesh.cpp
  python/test/unit/mesh/test_mixed_topology.py
Labels: enhancement, high-priority

#3009 Fix interior facet permutations
  cpp/dolfinx/fem/assemble_matrix_impl.h
  cpp/dolfinx/fem/assemble_vector_impl.h
  python/test/unit/fem/test_assembler.py
Labels: bug

#3003 Re-name overloaded `create_form` function
  cpp/dolfinx/fem/utils.h
  python/dolfinx/wrappers/fem.cpp
Labels: enhancement, housekeeping

#3024 Ensure that explicitly requested packages are enabled by CMake (and otherwise fail)
  cpp/CMakeLists.txt
Labels: build

#2517 Add Poisson matrix-free demo for Python
  cpp/demo/poisson_matrix_free/main.cpp
  python/demo/demo_poisson_matrix_free.py
Labels: demo
