Repository FEniCS/dolfinx, pull requests merged in 2024-11, with the labels that each got.

#3493 C++ style improvements in subdomain demo
  cpp/demo/codim_0_assembly/main.cpp
Labels: housekeeping

#3496 Simplify interface to `nanobind::ndarray`
  cpp/dolfinx/fem/Expression.h
  cpp/dolfinx/fem/utils.h
  python/dolfinx/geometry.py
  python/dolfinx/wrappers/array.h
  python/dolfinx/wrappers/assemble.cpp
  python/dolfinx/wrappers/common.cpp
  python/dolfinx/wrappers/fem.cpp
  python/dolfinx/wrappers/geometry.cpp
  python/dolfinx/wrappers/graph.cpp
  python/dolfinx/wrappers/la.cpp
  python/dolfinx/wrappers/mesh.cpp
Labels: housekeeping, nanobind

#3498 PETSc version bump to 3.22.1 in Dockerfiles
  docker/Dockerfile.redhat
  docker/Dockerfile.test-env
Labels: docker, ci

#3499 Demo updates for LU solver bugs
  .github/workflows/ccpp.yml
  cpp/dolfinx/common/Scatterer.h
  cpp/dolfinx/io/xdmf_utils.cpp
  cpp/dolfinx/io/xdmf_utils.h
  cpp/dolfinx/la/MatrixCSR.h
  cpp/dolfinx/la/SparsityPattern.h
  cpp/dolfinx/mesh/Geometry.h
  cpp/dolfinx/mesh/Mesh.h
  cpp/dolfinx/mesh/topologycomputation.cpp
  cpp/dolfinx/mesh/topologycomputation.h
  cpp/dolfinx/refinement/dolfinx_refinement.h
  docker/Dockerfile.test-env
  python/demo/demo_axis.py
  python/demo/demo_cahn-hilliard.py
  python/demo/demo_half_loaded_waveguide.py
  python/demo/demo_pml.py
  python/demo/demo_pyvista.py
  python/demo/demo_stokes.py
  python/dolfinx/fem/petsc.py
  python/dolfinx/wrappers/io.cpp
  python/test/unit/fem/test_petsc_solver_wrappers.py
Labels: demo, ci

#3503 Remove loguru and old pugixml references
  cpp/doc/Doxyfile
  sonar-project.properties
Labels: housekeeping

#3485 Remove `Fides` file backend
  cpp/dolfinx/io/ADIOS2Writers.cpp
  cpp/dolfinx/io/ADIOS2Writers.h
  cpp/dolfinx/io/vtk_utils.h
  cpp/test/io.cpp
  python/dolfinx/io/__init__.py
  python/dolfinx/io/utils.py
  python/dolfinx/wrappers/io.cpp
  python/test/unit/io/test_adios2.py
Labels: housekeeping, io

#3504 Expose set original cell index to python
  python/dolfinx/wrappers/mesh.cpp
Labels: nanobind

#3508 Improve readability of form in HDG demo
  python/demo/demo_hdg.py
Labels: demo

#3512 Improve Topology construction and fix MPI/NBX bug
  cpp/dolfinx/common/IndexMap.cpp
  cpp/dolfinx/common/IndexMap.h
  cpp/dolfinx/common/MPI.cpp
  cpp/dolfinx/common/MPI.h
  cpp/dolfinx/mesh/Topology.cpp
  cpp/dolfinx/mesh/Topology.h
  python/demo/demo_lagrange_variants.py
  python/dolfinx/wrappers/common.cpp
  python/dolfinx/wrappers/mesh.cpp
  python/test/unit/common/test_index_map.py
  python/test/unit/la/test_matrix_csr.py
Labels: enhancement

#3500 Add C++ demo that shows mixed elements and consistency fixes for element spaces
  .github/workflows/ccpp.yml
  cpp/demo/CMakeLists.txt
  cpp/demo/biharmonic/main.cpp
  cpp/demo/codim_0_assembly/main.cpp
  cpp/demo/custom_kernel/main.cpp
  cpp/demo/hyperelasticity/main.cpp
  cpp/demo/interpolation-io/main.cpp
  cpp/demo/interpolation_different_meshes/main.cpp
  cpp/demo/mixed_poisson/CMakeLists.txt
  cpp/demo/mixed_poisson/main.cpp
  cpp/demo/mixed_poisson/poisson.py
  cpp/demo/poisson/main.cpp
  cpp/demo/poisson_matrix_free/main.cpp
  cpp/doc/source/demo.rst
  cpp/dolfinx/fem/DirichletBC.h
  cpp/dolfinx/fem/FiniteElement.cpp
  cpp/dolfinx/fem/FiniteElement.h
  cpp/dolfinx/fem/Function.h
  cpp/dolfinx/fem/FunctionSpace.h
  cpp/dolfinx/fem/assemble_matrix_impl.h
  cpp/dolfinx/fem/assemble_scalar_impl.h
  cpp/dolfinx/fem/assemble_vector_impl.h
  cpp/dolfinx/fem/assembler.h
  cpp/dolfinx/fem/discreteoperators.h
  cpp/dolfinx/fem/dofmapbuilder.cpp
  cpp/dolfinx/fem/dofmapbuilder.h
  cpp/dolfinx/fem/interpolate.h
  cpp/dolfinx/fem/petsc.h
  cpp/dolfinx/fem/utils.cpp
  cpp/dolfinx/fem/utils.h
  cpp/dolfinx/io/ADIOS2Writers.h
  cpp/dolfinx/io/VTKFile.cpp
  cpp/dolfinx/io/xdmf_function.cpp
  cpp/dolfinx/mesh/generation.h
  cpp/dolfinx/mesh/utils.cpp
  cpp/dolfinx/mesh/utils.h
  cpp/dolfinx/refinement/interval.h
  cpp/dolfinx/refinement/plaza.h
  cpp/test/common/index_map.cpp
  cpp/test/fem/functionspace.cpp
  cpp/test/io.cpp
  cpp/test/matrix.cpp
  python/demo/demo_stokes.py
  python/dolfinx/fem/__init__.py
  python/dolfinx/fem/forms.py
  python/dolfinx/fem/function.py
  python/dolfinx/wrappers/assemble.cpp
  python/dolfinx/wrappers/fem.cpp
  python/dolfinx/wrappers/petsc.cpp
  python/test/unit/fem/test_assemble_mesh_independent_form.py
  python/test/unit/fem/test_assemble_submesh.py
  python/test/unit/fem/test_mixed_mesh_dofmap.py
  python/test/unit/fem/test_symmetric_tensor.py
Labels: enhancement, demo

#3513 Use separately allocated data for each call to MPI_Ineighbor_allgatherv
  cpp/dolfinx/fem/dofmapbuilder.cpp
Labels: bug

#3514 Fix doc typo
  python/dolfinx/io/gmshio.py
Labels: documentation

#3523 Fix topological dimension of vertex-meshes
  cpp/dolfinx/mesh/Topology.cpp
  python/test/unit/mesh/test_mesh.py
Labels: bug, high-priority

#3538 Fix domain id ordering of manually specified integration entities in Python
  python/dolfinx/fem/forms.py
  python/test/unit/fem/test_assemble_domains.py
Labels: enhancement
