Repository FEniCS/dolfinx, pull requests merged in 2025-09, with the labels that each got.

#3903 Drop Python 3.9 support
  .github/workflows/conda.yml
  python/dolfinx/common.py
  python/dolfinx/fem/assemble.py
  python/dolfinx/fem/bcs.py
  python/dolfinx/fem/element.py
  python/dolfinx/fem/forms.py
  python/dolfinx/fem/function.py
  python/dolfinx/fem/petsc.py
  python/dolfinx/geometry.py
  python/dolfinx/graph.py
  python/dolfinx/io/gmsh.py
  python/dolfinx/io/utils.py
  python/dolfinx/jit.py
  python/dolfinx/mesh.py
  python/dolfinx/plot.py
  python/pyproject.toml
  python/test/unit/fem/test_function_space.py
  sonar-project.properties
Labels: housekeeping

#3907 Fix type hint regression
  python/dolfinx/fem/forms.py
Labels: type-hints

#3914 Remove dynamic memory allocation in lowest-level scalar assembly functions
  cpp/dolfinx/fem/assemble_scalar_impl.h
Labels: performance

#3905 Ensure `dolfinx` does not expose warning to user
  .github/workflows/ccpp.yml
  .github/workflows/ci-spack.yml
  .github/workflows/macos.yml
  python/dolfinx/io/__init__.py
  python/dolfinx/io/gmshio.py
  python/dolfinx/utils.py
  python/test/unit/fem/test_expression.py
  python/test/unit/fem/test_petsc_solver_wrappers.py
  python/test/unit/nls/test_newton.py
Labels: python

#3937 `DirichletBC.dof_indices()` are wrong for blocked spaces
  cpp/dolfinx/fem/DirichletBC.h
  python/test/unit/fem/test_bcs.py
Labels: high-priority
