Repository FEniCS/dolfinx, pull requests merged in 2025-03, with the labels that each got.

#3649 Simplify assembler implementation interfaces
  cpp/demo/custom_kernel/main.cpp
  cpp/dolfinx/fem/assemble_matrix_impl.h
  cpp/dolfinx/fem/assemble_scalar_impl.h
  cpp/dolfinx/fem/assemble_vector_impl.h
  cpp/dolfinx/fem/assembler.h
  python/dolfinx/wrappers/dolfinx_wrappers/pycoeff.h
  python/test/unit/fem/test_expression.py
Labels: housekeeping

#3604 Extend the mesh generation testing to the 3D cases
  cpp/test/mesh/generation.cpp
Labels: ci

#3600 Expose `_bbox_coordinates` of `BoundingBoxTree` to users
  cpp/dolfinx/geometry/BoundingBoxTree.h
  cpp/dolfinx/geometry/utils.h
  python/dolfinx/geometry.py
  python/dolfinx/wrappers/geometry.cpp
  python/test/unit/geometry/test_bounding_box_tree.py
Labels: enhancement

#3658 Unpin Sphinx version.
  python/pyproject.toml
Labels: documentation, housekeeping

#3662 Add support for Serendipity (order 2) coordinate elements
  cpp/dolfinx/io/cells.cpp
  cpp/dolfinx/io/xdmf_utils.cpp
  python/dolfinx/io/utils.py
Labels: enhancement

#3665 Improve code clarity in cell maps/permutations
  cpp/dolfinx/io/cells.cpp
  cpp/dolfinx/io/cells.h
Labels: housekeeping

#3667 Unify PETSc matrix and vector factory functions
  cpp/dolfinx/fem/petsc.h
  cpp/dolfinx/la/petsc.cpp
  cpp/dolfinx/la/petsc.h
  python/demo/demo_stokes.py
  python/dolfinx/fem/petsc.py
  python/dolfinx/wrappers/petsc.cpp
  python/test/unit/fem/test_assembler.py
  python/test/unit/fem/test_petsc_nonlinear_assembler.py
Labels: housekeeping

#3669 Require `clang-format` CI checks to pass
  .github/workflows/ccpp.yml
  cpp/demo/custom_kernel/main.cpp
  cpp/dolfinx/common/Scatterer.h
  cpp/dolfinx/common/types.h
  cpp/dolfinx/fem/DirichletBC.h
  cpp/dolfinx/fem/Expression.h
  cpp/dolfinx/fem/Function.h
  cpp/dolfinx/fem/assembler.h
  cpp/dolfinx/fem/discreteoperators.h
  cpp/dolfinx/fem/traits.h
  cpp/dolfinx/fem/utils.h
  cpp/dolfinx/la/Vector.h
  cpp/dolfinx/mesh/Topology.h
  cpp/test/mesh/read_named_meshtags.cpp
  python/dolfinx/wrappers/fem.cpp
Labels: ci
