Repository FEniCS/dolfinx, pull requests merged in 2025-08, with the labels that each got.

#3863 Fix indentation of create_mesh
  python/dolfinx/mesh.py
Labels: documentation

#3740 Refactor `dolfinx::fem::Form` to use local indexing of forms, rather than integral ids
  cpp/demo/custom_kernel/main.cpp
  cpp/dolfinx/fem/Form.h
  cpp/dolfinx/fem/assemble_matrix_impl.h
  cpp/dolfinx/fem/assemble_scalar_impl.h
  cpp/dolfinx/fem/assemble_vector_impl.h
  cpp/dolfinx/fem/pack.h
  cpp/dolfinx/fem/utils.h
  python/demo/demo_static-condensation.py
  python/dolfinx/fem/forms.py
  python/dolfinx/wrappers/fem.cpp
  python/test/unit/fem/test_assembler.py
  python/test/unit/fem/test_custom_jit_kernels.py
Labels: enhancement, high-priority

#3879 Make tests work as standalone project
  .github/workflows/ccpp.yml
  cpp/test/CMakeLists.txt
Labels: testing, build

#3887 Rocky -> AlmaLinux for CI
  .github/workflows/ci-spack.yml
  .github/workflows/macos.yml
  .github/workflows/spack-config/gh-actions-rh.yml
Labels: ci

#3884 CI testing via Spack (experimental)
  .github/workflows/ccpp.yml
  .github/workflows/ci-spack.yml
  .github/workflows/ci.yml
  .github/workflows/macos.yml
  .github/workflows/spack-config/gh-actions-env-test.yml
  .github/workflows/windows.yml
  cpp/test/CMakeLists.txt
  python/CMakeLists.txt
Labels: ci
