Repository FEniCS/dolfinx, pull requests merged in 2025-02, with the labels that each got.

#3613 Find ADIOS2 CXX only
  cpp/CMakeLists.txt
  cpp/cmake/templates/DOLFINXConfig.cmake.in
Labels: build

#3614 Bump versions in Dockerfile
  docker/Dockerfile.redhat
  docker/Dockerfile.test-env
Labels: docker

#3617 Use strict compiler flags when building nanobind layer in Debug mode.
  cpp/CMakeLists.txt
  python/CMakeLists.txt
  python/dolfinx/wrappers/fem.cpp
  python/dolfinx/wrappers/io.cpp
Labels: build, nanobind

#3622 Require `nanobind>=2.5.0`
  python/build-requirements.txt
  python/pyproject.toml
Labels: install, housekeeping, nanobind, dependencies

#3626 Update documentation in petsc.py
  python/dolfinx/fem/petsc.py
Labels: documentation

#3635 Unpin cffi version (fixes tests for Python 3.13)
  python/conda-oneapi-test-env.yml
  python/demo/demo_static-condensation.py
  python/pyproject.toml
  python/test/unit/fem/test_custom_assembler.py
Labels: build, python

#3633 Add checks on geometry element for generated code
  cpp/dolfinx/fem/CoordinateElement.cpp
  cpp/dolfinx/fem/CoordinateElement.h
  cpp/dolfinx/fem/FiniteElement.cpp
  cpp/dolfinx/fem/FiniteElement.h
  cpp/dolfinx/fem/Form.h
  cpp/dolfinx/fem/petsc.cpp
  cpp/dolfinx/fem/utils.h
  cpp/test/CMakeLists.txt
  cpp/test/fem/expr.py
  cpp/test/fem/form.cpp
  python/dolfinx/fem/element.py
  python/dolfinx/io/utils.py
  python/dolfinx/io/vtkhdf.py
  python/dolfinx/mesh.py
  python/dolfinx/wrappers/assemble.cpp
  python/dolfinx/wrappers/fem.cpp
Labels: enhancement

#3636 Update oneAPI CI
  python/conda-oneapi-test-env.yml
Labels: ci

#3639 Doc fixes and pin Sphinx version
  cpp/demo/mixed_poisson/CMakeLists.txt
  cpp/demo/mixed_poisson/main.cpp
  cpp/demo/mixed_poisson/mixed_poisson.py
  cpp/doc/source/demo.rst
  python/pyproject.toml
Labels: bug, documentation

#3625 Move `Expression::eval` to a free function with other 'assemblers'
  cpp/dolfinx/fem/CMakeLists.txt
  cpp/dolfinx/fem/Expression.h
  cpp/dolfinx/fem/Function.h
  cpp/dolfinx/fem/assemble_expression_impl.h
  cpp/dolfinx/fem/assemble_vector_impl.h
  cpp/dolfinx/fem/assembler.h
  cpp/dolfinx/fem/pack.h
  cpp/dolfinx/fem/traits.h
  cpp/dolfinx/fem/utils.h
  cpp/test/fem/form.cpp
  python/CMakeLists.txt
  python/dolfinx/fem/function.py
  python/dolfinx/wrappers/assemble.cpp
  python/dolfinx/wrappers/fem.cpp
  python/test/unit/fem/test_expression.py
Labels: enhancement, proposal

#3646 Performance fixes and simplifications for `fem::Form`
  cpp/demo/custom_kernel/main.cpp
  cpp/dolfinx/fem/Form.h
  cpp/dolfinx/fem/assemble_matrix_impl.h
  cpp/dolfinx/fem/assemble_scalar_impl.h
  cpp/dolfinx/fem/assemble_vector_impl.h
  cpp/dolfinx/fem/pack.h
  cpp/dolfinx/fem/utils.h
  python/demo/demo_static-condensation.py
  python/dolfinx/fem/forms.py
  python/dolfinx/wrappers/fem.cpp
  python/test/unit/fem/test_assemble_submesh.py
  python/test/unit/fem/test_custom_jit_kernels.py
Labels: bug, performance, housekeeping
