Repository FEniCS/dolfinx, pull requests merged in 2025-04, with the labels that each got.

#3681 Small doc improvement
  python/dolfinx/fem/assemble.py
  python/dolfinx/fem/petsc.py
Labels: documentation

#3680 Correct usage of input coefficients for `apply_lifting` of blocked operators.
  python/dolfinx/fem/petsc.py
  python/test/unit/fem/test_assembler.py
Labels: bug

#3683 Block assembly with no DirichletBC and None on diagonal
  python/dolfinx/fem/petsc.py
  python/test/unit/fem/test_assembler.py
Labels: bug

#3685 Update pyvista.yml
  .github/workflows/pyvista.yml
Labels: ci

#3690 Fixes for mypy
  python/dolfinx/fem/forms.py
  python/dolfinx/jit.py
Labels: housekeeping, ci, type-hints

#3693 Stokes demo: create PETSc IS on mesh communicator
  python/demo/demo_stokes.py
Labels: bug, demo

#3695 Simplify SCOTCH configuration
  .github/workflows/macos.yml
  cpp/CMakeLists.txt
  cpp/cmake/modules/FindSCOTCH.cmake
Labels: build

#3686 Extend VTKHDF file format to read/write higher order grids
  cpp/dolfinx/io/VTKHDF.h
  cpp/dolfinx/io/cells.cpp
  cpp/dolfinx/io/cells.h
  python/dolfinx/io/vtkhdf.py
  python/dolfinx/wrappers/io.cpp
  python/test/unit/io/test_vtkhdf.py
Labels: enhancement, io

#3700 Various code fixes and simplifications
  cpp/dolfinx/common/MPI.h
  cpp/dolfinx/common/Scatterer.h
  cpp/dolfinx/fem/FunctionSpace.h
  cpp/dolfinx/fem/discreteoperators.h
  cpp/dolfinx/io/HDF5Interface.cpp
  cpp/dolfinx/io/HDF5Interface.h
  cpp/dolfinx/io/VTKHDF.h
  cpp/dolfinx/la/MatrixCSR.h
  cpp/dolfinx/mesh/generation.h
  cpp/dolfinx/mesh/utils.h
  python/dolfinx/wrappers/assemble.cpp
  python/dolfinx/wrappers/dolfinx_wrappers/array.h
  python/dolfinx/wrappers/fem.cpp
  python/dolfinx/wrappers/io.cpp
  python/dolfinx/wrappers/mesh.cpp
  python/dolfinx/wrappers/petsc.cpp
Labels: housekeeping

#3702 Remove 'bug' label. 'bug' is now an issue type.
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: housekeeping

#3703 Get CMake to print some output when SCOTCH is found
  cpp/CMakeLists.txt
Labels: build

#3705 Improve SCOTCH handling in CMake
  cpp/CMakeLists.txt
Labels: build
