Repository FEniCS/dolfinx, pull requests merged in 2025-01, with the labels that each got.

#3586 Spelling fixes
  ChangeLog.rst
  cpp/CMakeLists.txt
  cpp/doc/Doxyfile
  cpp/doc/source/jupytext_process.py
  cpp/dolfinx/common/IndexMap.cpp
  cpp/dolfinx/common/sort.h
  cpp/dolfinx/fem/DirichletBC.h
  cpp/dolfinx/fem/FiniteElement.h
  cpp/dolfinx/fem/Form.h
  cpp/dolfinx/fem/interpolate.h
  cpp/dolfinx/graph/partitioners.cpp
  cpp/dolfinx/io/XDMFFile.cpp
  cpp/dolfinx/io/xdmf_function.cpp
  cpp/dolfinx/io/xdmf_mesh.cpp
  cpp/dolfinx/la/Vector.h
  cpp/dolfinx/mesh/Geometry.h
  cpp/dolfinx/mesh/utils.h
  python/demo/demo_half_loaded_waveguide.py
  python/demo/demo_hdg.py
  python/demo/demo_navier-stokes.py
  python/demo/demo_poisson_matrix_free.py
  python/demo/demo_stokes.py
  python/dolfinx/io/gmshio.py
  python/dolfinx/mesh.py
  python/test/unit/fem/test_assembler.py
  python/test/unit/mesh/test_mesh.py
  python/test/unit/mesh/test_meshtags.py
Labels: housekeeping

#3580 Use block preconditioner for mixed Poisson problem
  .github/workflows/ccpp.yml
  .github/workflows/macos.yml
  cpp/dolfinx/fem/assemble_vector_impl.h
  cpp/dolfinx/fem/discreteoperators.h
  python/demo/demo_half_loaded_waveguide.py
  python/demo/demo_mixed-poisson.py
  python/demo/demo_poisson.py
  python/demo/demo_stokes.py
  python/dolfinx/fem/dofmap.py
  python/dolfinx/fem/forms.py
  python/dolfinx/fem/function.py
  python/dolfinx/fem/petsc.py
  python/dolfinx/graph.py
  python/dolfinx/mesh.py
  python/dolfinx/plot.py
  python/test/conftest.py
  python/test/unit/fem/test_assembler.py
Labels: demo

#3532 Fix inconsistent ufl usage in demos
  python/demo/demo_biharmonic.py
  python/demo/demo_cahn-hilliard.py
  python/demo/demo_elasticity.py
  python/demo/demo_hdg.py
  python/demo/demo_helmholtz.py
  python/demo/demo_lagrange_variants.py
  python/demo/demo_mixed-poisson.py
  python/demo/demo_navier-stokes.py
  python/demo/demo_poisson.py
  python/demo/demo_poisson_matrix_free.py
  python/demo/demo_pyamg.py
  python/demo/demo_stokes.py
  python/demo/demo_tnt-elements.py
  python/demo/pyproject.toml
Labels: demo, housekeeping, python

#3591 Move SpMV from tests into MatrixCSR
  cpp/dolfinx/la/MatrixCSR.h
  cpp/dolfinx/la/matrix_csr_impl.h
  cpp/test/CMakeLists.txt
  cpp/test/matrix.cpp
  python/dolfinx/la.py
  python/dolfinx/wrappers/la.cpp
  python/test/unit/fem/test_discrete_operators.py
  python/test/unit/la/test_matrix_vector.py
Labels: enhancement

#3587 Add discrete curl matrix operator
  cpp/dolfinx/fem/CoordinateElement.h
  cpp/dolfinx/fem/discreteoperators.h
  cpp/dolfinx/fem/interpolate.h
  python/dolfinx/fem/__init__.py
  python/dolfinx/fem/petsc.py
  python/dolfinx/wrappers/assemble.cpp
  python/dolfinx/wrappers/petsc.cpp
  python/test/unit/fem/test_discrete_operators.py
Labels: enhancement

#3592 Version bumps in Dockerfile
  docker/Dockerfile.test-env
Labels: docker

#3596 Tidy up sparse matrix code
  cpp/dolfinx/la/MatrixCSR.h
  cpp/dolfinx/la/matrix_csr_impl.h
Labels: housekeeping

#3597 Fix mapping of coefficients and constants for form independent compilation.
  python/dolfinx/fem/forms.py
  python/test/unit/fem/test_assemble_mesh_independent_form.py
Labels: bug, backport?

#3590 More work towards supporting mixed-topology meshes
  cpp/dolfinx/fem/Form.h
  cpp/dolfinx/fem/FunctionSpace.h
  cpp/dolfinx/fem/assemble_matrix_impl.h
  cpp/dolfinx/fem/assembler.h
  cpp/dolfinx/fem/utils.h
  cpp/dolfinx/mesh/Geometry.h
  cpp/dolfinx/mesh/Topology.cpp
  cpp/dolfinx/mesh/Topology.h
  python/demo/demo_mixed-topology.py
  python/doc/source/demos.rst
  python/dolfinx/fem/__init__.py
  python/dolfinx/fem/forms.py
  python/dolfinx/wrappers/assemble.cpp
  python/dolfinx/wrappers/fem.cpp
  python/dolfinx/wrappers/mesh.cpp
  python/test/unit/fem/test_forms.py
Labels: enhancement
