Repository FEniCS/dolfinx, pull requests merged in 2025-07, with the labels that each got.

#3781 Remove duplicate lines from `fem/petsc.py`
  python/dolfinx/fem/petsc.py
Labels: housekeeping

#3785 Add mandatory options prefix to high-level solver classes and general tidy
  python/demo/demo_axis.py
  python/demo/demo_biharmonic.py
  python/demo/demo_cahn-hilliard.py
  python/demo/demo_helmholtz.py
  python/demo/demo_mixed-poisson.py
  python/demo/demo_navier-stokes.py
  python/demo/demo_pml.py
  python/demo/demo_poisson.py
  python/demo/demo_scattering_boundary_conditions.py
  python/demo/demo_stokes.py
  python/demo/demo_tnt-elements.py
  python/dolfinx/fem/petsc.py
  python/dolfinx/la/petsc.py
  python/test/unit/fem/test_petsc_nonlinear_assembler.py
  python/test/unit/fem/test_petsc_solver_wrappers.py
Labels: housekeeping

#3804 Move conda/oneAPI CI config file
  .github/workflows/oneapi-conda/environment.yml
  .github/workflows/oneapi.yml
Labels: housekeeping, ci

#3816 Simplify import in Python demos
  .github/workflows/ccpp.yml
  .github/workflows/oneapi-conda/environment.yml
  .github/workflows/oneapi.yml
  .github/workflows/redhat.yml
  cpp/dolfinx/mesh/graphbuild.cpp
  python/demo/demo_axis.py
  python/demo/demo_biharmonic.py
  python/demo/demo_cahn-hilliard.py
  python/demo/demo_elasticity.py
  python/demo/demo_gmsh.py
  python/demo/demo_half_loaded_waveguide.py
  python/demo/demo_hdg.py
  python/demo/demo_helmholtz.py
  python/demo/demo_interpolation-io.py
  python/demo/demo_mixed-poisson.py
  python/demo/demo_navier-stokes.py
  python/demo/demo_pml.py
  python/demo/demo_poisson.py
  python/demo/demo_pyamg.py
  python/demo/demo_pyvista.py
  python/demo/demo_scattering_boundary_conditions.py
  python/demo/demo_static-condensation.py
  python/demo/demo_stokes.py
  python/demo/demo_tnt-elements.py
  python/demo/demo_types.py
  python/demo/test.py
Labels: demo, ci, python

#3817 More complete Rocky (Redhat) image
  docker/Dockerfile.redhat
  python/demo/demo_half_loaded_waveguide.py
Labels: ci

#3803 Create parallel communication graph and support NetworkX analysis and visualiation
  .github/workflows/oneapi-conda/environment.yml
  cpp/demo/hyperelasticity/main.cpp
  cpp/dolfinx/common/IndexMap.cpp
  cpp/dolfinx/common/IndexMap.h
  cpp/dolfinx/common/MPI.h
  cpp/dolfinx/common/Scatterer.h
  cpp/dolfinx/common/Timer.h
  cpp/dolfinx/common/utils.h
  cpp/dolfinx/graph/AdjacencyList.h
  cpp/dolfinx/graph/CMakeLists.txt
  cpp/dolfinx/graph/ordering.cpp
  cpp/dolfinx/graph/utils.cpp
  cpp/dolfinx/graph/utils.h
  cpp/test/common/index_map.cpp
  cpp/test/graph.cpp
  python/demo/demo_comm-pattern.py
  python/demo/demo_elasticity.py
  python/demo/demo_half_loaded_waveguide.py
  python/demo/demo_poisson_matrix_free.py
  python/demo/demo_pyamg.py
  python/demo/demo_stokes.py
  python/doc/source/demos.rst
  python/dolfinx/graph.py
  python/dolfinx/io/gmshio.py
  python/dolfinx/la/petsc.py
  python/dolfinx/mesh.py
  python/dolfinx/wrappers/common.cpp
  python/dolfinx/wrappers/graph.cpp
  python/pyproject.toml
Labels: enhancement, demo

#3818 Revert `python/CMakeLists.txt` change made in #3756
  python/CMakeLists.txt
Labels: build

#3824 Remove pyvista-specific CI (covered elsewhere)
  .github/workflows/pyvista.yml
Labels: ci

#3834 Correct several typos in Stokes example and improve documentation formatting
  python/demo/demo_stokes.py
Labels: documentation

#3835 Improve CMake find modules
  .github/workflows/ccpp.yml
  .github/workflows/ci-spack.yml
  .github/workflows/macos.yml
  cpp/CMakeLists.txt
  cpp/cmake/modules/FindKaHIP.cmake
  cpp/cmake/modules/FindParMETIS.cmake
  cpp/cmake/scripts/generate-cmakefiles.py
  cpp/cmake/templates/DOLFINXConfig.cmake.in
  cpp/cmake/templates/dolfinx.pc.in
  cpp/demo/biharmonic/CMakeLists.txt
  cpp/demo/codim_0_assembly/CMakeLists.txt
  cpp/demo/custom_kernel/CMakeLists.txt
  cpp/demo/hyperelasticity/CMakeLists.txt
  cpp/demo/interpolation-io/CMakeLists.txt
  cpp/demo/interpolation_different_meshes/CMakeLists.txt
  cpp/demo/mixed_poisson/CMakeLists.txt
  cpp/demo/poisson/CMakeLists.txt
  cpp/demo/poisson_matrix_free/CMakeLists.txt
  cpp/dolfinx/CMakeLists.txt
  cpp/dolfinx/common/version.h.in
  cpp/test/CMakeLists.txt
Labels: build
